### ISSUE TITLE
The host parameter in bindings section is not being passed to the service

### ISSUE THREAD

**Issue by robertsundstrom** [dotnet/tye#1006]
### Describe the bug
The  ```host``` parameter in ```bindings``` section in tye.yml is not passed to the service/app.

As a result the service is not binding to the specified IP address or hostname, and is still ```localhost```.

The issue was first reported in #721 . There you find more details about what line of code.

### To Reproduce

Create a web project:

```
dotnet new web -o TestWebApp
cd TestWebApp
```

This is optional (just copy the config below):

```
tye init
```

Add the bindings section (substitute YOUR-IP-ADDRESS with your own IP Address or host name):

```
name: testwebapp
services:
- name: testwebapp
  project: TestWebApp.csproj
  bindings:
    - name: Test
      host: <YOUR-IP-ADDRESS>
      port: 5643
```

### Further technical details

Tye version: 0.7.0-alpha.21205.1+ad2d7cac132e46d9bd9e1c1c064fd19f35459307.
.NET version: 5.0.200
