### ISSUE TITLE
Dockerfile build ignores actual docker file value

### ISSUE THREAD

**Issue by flipch** [dotnet/tye#1012]
Independent of what the value is on the dockerFile setting in your tye.yaml, you'll always try to find a dockerfile with the name `Dockerfile`. 

https://github.com/dotnet/tye/blob/ad3f692d53ab1dd5bca5c2508d47c287777a7e40/src/Microsoft.Tye.Core/DockerContainerBuilder.cs#L39

```
services:
  - name: example
    dockerFile: example/Dockerfile.dev
``` 

Will result in ` failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount438065623/Dockerfile: no such file or directory`

**Comment by flipch** [comment]
Also worth nothing that even though a dotnet project does not have any dockerfile settings set it'll still use the docker image if available instead of using the default behaviour.

```
  - name: example-api
    project: example-api/example-api.csproj 
    bindings:
      - port: 5001 
        protocol: https
 ```

If I have a Dockerfile inside of example-api/ it'll try to build that image and fail due to relative paths. Is this intended behaviour?
