### ISSUE TITLE
exception when I try to get started

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/tye#1024]
### Describe the bug

Exception when I try to get started...

### To Reproduce

Just installed the tool via `dotnet tool install -g Microsoft.Tye --version "0.6.0-alpha.21070.5"`, and then try to run `tye run` in the solution dir, but got the exception below:

![image](https://user-images.githubusercontent.com/7604648/116672782-24797580-a9d5-11eb-8e57-b899adc2ddb0.png)

### Further technical details

- Include the output of `tye --version`: `0.6.0-alpha.21070.5+a42e4463943e3136dbd1de38474d8d62b802797c`
- If possible rerun the command with `-v debug` and include the output:
![image](https://user-images.githubusercontent.com/7604648/116673101-8afe9380-a9d5-11eb-8916-d369863d0c7d.png)

- The platform: `Windows`

**Comment by davidfowl** [comment]
Do you have .net 5 installed?

**Comment by WeihanLi** [comment]
Yeah, the `dotnet --info` output is as follows:

![image](https://user-images.githubusercontent.com/7604648/116674368-247a7500-a9d7-11eb-83b3-bda6f66d1052.png)

**Comment by BenLocal** [comment]
I got the same issues,after create a tye.yaml, then run successfully

**Comment by jkotalik** [comment]
We are actively looking into this, seems to be an issue when the 6.0 preview SDK is installed. We had a dependency still on msbuild in-process, which we are trying to remove.

@davidfowl see https://github.com/dotnet/tye/pull/1008 for my attempt of a fix. It's spicy.

**Comment by jkotalik** [comment]
To work around for now, you'd need to uninstall the 6.0-preview SDK (or maybe a global.json file would work, but I haven't tried).

**Comment by WeihanLi** [comment]
Thanks @jkotalik , add a `global.json` with the content below, no exception like before

``` json
{
  "sdk": {
    "version": "5.0.100",
    "rollForward": "latestFeature"
  }
}
```

but got another error, seemed that it's because of my `Dockerfile` is not in the right place? My project is [here](https://github.com/WeihanLi/SparkTodo/) if you wanna have a look.

![image](https://user-images.githubusercontent.com/7604648/116767539-520d0000-aa63-11eb-9570-535807206687.png)

**Comment by WeihanLi** [comment]
I met another problem with docker-compose, I can start my app via `docker-compose up` but not with tye.
It seemed there's network issue from the error log

![image](https://user-images.githubusercontent.com/7604648/116768487-8aafd800-aa69-11eb-88a5-166af192bcf7.png)

I add a link for the redis dependency in the `docker-compose.yml`, the compose file is as follows, you can find my project here <https://github.com/OpenReservation/ReservationServer>

``` yaml
version: '2.1'
services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    healthcheck:
        test: ["CMD", "redis-cli", "-h", "127.0.0.1", "PING"]
        interval: 30s
        timeout: 10s
        retries: 10

  db:
    container_name: mysql
    image: mysql:8.0
    environment:
      - 'MYSQL_ROOT_PASSWORD=Admin888'
    restart: always
    healthcheck:
        test: ["CMD", "mysqladmin", "ping"]
        interval: 30s
        timeout: 10s
        retries: 10

  reservation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reservation
    environment:
      - 'Reservation_AppSettings__DbType=MySql'
      - 'Reservation_ConnectionStrings__ElasticSearch='
      - 'Reservation_ConnectionStrings__Reservation=server=db-server;database=Reservation;uid=root;pwd=Admin888;'
      - 'Reservation_ConnectionStrings__Redis=redis-server'
    ports:
      - 65026:80
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    links: 
      - db:db-server
      - redis:redis-server
      
```
