### ISSUE TITLE
Configure service for remote access?

### ISSUE THREAD

**Issue by robertsundstrom** [dotnet/tye#1052]
How do I configure Tye so that I can connect to services from a remote device on the same network. For instance, a mobile phone.

I'm developing a mobile app.

**Comment by theperm** [comment]
Thats a very vague question, it would all depend on how you use tye, are u deploying into k8s? You would need to describe your env a bit more.

**Comment by daniel-simpson** [comment]
I'd suggest you check out this project: https://github.com/wernight/docker-ngrok

You can run this as a docker image on your local in order to get an externally resolveable address that you can use in your app to talk to your local services.

I'd suggest running this outside of tye (with docker directly), but if you need to you could add something like the following to your tye yaml:

Example in Tye:
```yaml
  - name: ngrok
    image: wernight/ngrok
    env:
      - "NGROK_PROTOCOL=<your service protocol, e.g. HTTP>"
      - "NGROK_PORT=<your backend service name, e.g. backend>"
```

Once it's running, check the console output from the ngrok container in order to get your address to use in your app
