### ISSUE TITLE
Add `-app-ssl` flag for Dapr extension

### ISSUE THREAD

**Issue by mikalst** [dotnet/tye#1065]
### What should we add or change to make your life better?
Enable support for running daprd with argument `-app-ssl ` using Tye.

The template file
```yaml
name: ms.sample.webapi

extensions:
- name: dapr
  components-path: "./components/"
  log-level: debug
  app-ssl: true # <--- This is what I'm talking about

services:
- name: receiverwebapi
  project: ReceiverWebApi/ReceiverWebApi.csproj
- name: senderwebapi
  project: SenderWebApi/SenderWebApi.csproj
  ```

currently produces
`
daprd.exe -app-id receiverwebapi -app-port 2172 -dapr-grpc-port 2176 --dapr-http-port 2177 --metrics-port 2178 --placement-host-address localhost:2171 -log-level debug -components-path ./components/
`

but I want it  to produce
`
daprd.exe -app-id receiverwebapi -app-port 2173 -dapr-grpc-port 2176 --dapr-http-port 2177 --metrics-port 2178 --placement-host-address localhost:2171 -app-ssl -log-level debug -components-path ./components/
`

thereby targetting the HTTPS port (2173) of the application for any method / binding invocations.

### Why is this important to you?
I don't want to turn of https redirection in my web api.
