### ISSUE TITLE
Loading external repository with Dockerfile located in a subfolder

### ISSUE THREAD

**Issue by vova-lantsov-dev** [dotnet/tye#1143]
I have the following `tye.yaml`:
```yaml
name: test_app
services:
  - name: host
    dockerFile: TestProj.AppHost/Dockerfile
    dockerFileContext: .
    bindings:
      - port: 6003
  - name: ui
    repository: ssh://.../....git
    dockerFile: docker/Dockerfile
    dockerFileContext: .
    bindings:
      - port: 8080
  - name: postgres
    image: postgres:13.3-alpine
    args: "-c shared_buffers=512MB -c max_connections=500"
    env:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test-app
    env_file:
      - ./tye-postgres.env
    bindings:
      - port: 5432
    volumes:
      - name: test-postgres-volume
        target: /var/lib/postgresql/data
```
The problem is with `ui` service. It has a Dockerfile, but it is not located in the root of cloned repository, but in `docker` subfolder.

---
I also tried to create a separate `tye.yaml` in UI repository:
```yaml
name: test_app
services:
  - name: ui
    dockerFile: docker/Dockerfile
    dockerFileContext: .
    bindings:
      - port: 8080
```
And then remove dockerfile options from main config:
```yaml
name: test_app
services:
  - name: host
    dockerFile: TestProj.AppHost/Dockerfile
    dockerFileContext: .
    bindings:
      - port: 6003
  - name: ui
    repository: ssh://.../....git
    bindings:
      - port: 8080
  - name: postgres
    image: postgres:13.3-alpine
    args: "-c shared_buffers=512MB -c max_connections=500"
    env:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test-app
    env_file:
      - ./tye-postgres.env
    bindings:
      - port: 5432
    volumes:
      - name: test-postgres-volume
        target: /var/lib/postgresql/data
```
but it didn't help

---
And also I tried to set the path including `.tye/deps/ui` prefix:
```yaml
name: test_app
services:
  - name: host
    dockerFile: TestProj.AppHost/Dockerfile
    dockerFileContext: .
    bindings:
      - port: 6003
  - name: ui
    repository: ssh://.../....git
    dockerFile: .tye/deps/ui/docker/Dockerfile
    dockerFileContext: .tye/deps/ui
    bindings:
      - port: 8080
  - name: postgres
    image: postgres:13.3-alpine
    args: "-c shared_buffers=512MB -c max_connections=500"
    env:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test-app
    env_file:
      - ./tye-postgres.env
    bindings:
      - port: 5432
    volumes:
      - name: test-postgres-volume
        target: /var/lib/postgresql/data
```
It doesn't work as well.

---
Tye version is: 0.8.0-alpha.21352.1
Docker engine: v20.10.7
Kubernetes: v1.21.2
OS: macOS Big Sur 11.5.1
Model: MacBook Air (M1, 2020), arm64 architecture

---
Log from Tye dashboard:
```
#2 [internal] load .dockerignore
#2 sha256:60ba320a4bdd6444fa7d99271891e685189aa09614bf22c614672ca703d4773a
#2 transferring context: 2B done
#2 DONE 1.4s
#1 [internal] load build definition from Dockerfile
#1 sha256:38a6123200ebb9771709d7f21a22d31e8636f319381f7458c608de63804aba3f
#1 transferring dockerfile: 2B done
#1 DONE 1.7s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount228772700/Dockerfile: no such file or directory
```
