### ISSUE TITLE
Tye Ingress generated k8 yaml using deprecated apiVersion?

### ISSUE THREAD

**Issue by xavidram** [dotnet/tye#1147]
### Describe the bug
I have been trying to use the `tye deploy` with an ingress section but it fails during the validation step when trying to build the k8 config. After looking at the basic documentation [here](https://kubernetes.github.io/ingress-nginx/user-guide/basic-usage/) I see that tye uses an old version? I am rather new to kubernetes so I am learning as I go. 

### To Reproduce
1. Create a tye.yaml and add in ingress section similar to this:
```
name: testapp
namespace: testapp
registry: registry.digitalocean.com/testapp

ingress:
- name: ingress
  bindings:
  - port: 443
    protocol: https
  rules:
  - host: example.local
    service: webapp

extensions:
- name: dapr
  log-level: debug
  config: appconfig
  components-path: "./components"

services:
- name: webapp
  project: src/Web/TestApp/Server/TestApp.Server.csproj
  bindings:
    - name: https
      port: 3001
      protocol: https
    - name: http
      port: 3000
      protocol: http

```

2. Try and deploy to a kubernetes instance with `tye deploy` and it should fail.
3. Generate the k8 config using `tye generate` and look specifically at the ingress section. Should appear like this

```
...
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: testapp
  namespace: testapp
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/rewrite-target: '/$2'
  labels:
    app.kubernetes.io/part-of: 'testapp'
spec:
  rules:
  - host: example.local
    http:
      paths:
      - backend:
          serviceName: webapp
          servicePort: 3000
        path: /()(.*)
...
```

When i read the Nginx documentation for api deprecation  I see that `extensions/v1beta1` is deprecated and instead to use `networking.k8s.io/v1`

### Further technical details

- Tye version: 0.9.0-alpha.21380.1+836b0baa8a0ed5d8ca3bebc27c7d4f6d0a7bdfd9
- Kubernetes version: 1.21.2
- Platform: Window 10

**Comment by xavidram** [comment]
I also noticed that the ingress ends up missing some fields. I had to update the generated ingress ection of the k8 file to the following

```
...
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: testapp
  namespace: testapp
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/rewrite-target: '/$2'
  labels:
    app.kubernetes.io/part-of: 'testapp'
spec:
  rules:
  - host: example.local
    http:
      paths:
      - backend:
          service:
            name: webapp
            port:
              number: 3001
        path: /()(.*)
        pathType: Prefix
```

The ingress section did not know what `serviceName` was, it needed to be split into a `service` section with the `name` and `port` described. And it was missing the `pathType` which in this case was prefix.
