### ISSUE TITLE
tye run with dapr (self host)

### ISSUE THREAD

**Issue by LGinC** [dotnet/tye#1155]
dapr 1.12 self host (`dapr init --slim`)  without docker
tye.yml
```yaml
name: product-blog
extensions:
- name: dapr
services:
- name: product
  project: microservices/ProductService.Host/ProductService.Host.csproj
  bindings:
  - port: 44344
    protocol: https
- name: blogging
  project: microservices/BloggingService.Host/BloggingService.Host.csproj
  bindings:
  - port: 44357
    protocol: https
```

and run this `tye run tye.yml`
```powershell
[16:40:23 ERR] Unable to pull image: container engine is not installed..
Drats! 'run' failed:
        Unable to pull image: container engine is not installed..
```

**Comment by LGinC** [comment]
I have a question, how to assign http port of dapr app.
`dapr run --app-id=product -H 3500 -p 44357 --app-ssl=true -- dotnet run`  like this

**Comment by xavidram** [comment]
Based on your current configuration you can do something like this if you need both http and https

```
name: product-blog
extensions:
- name: dapr
services:
- name: product
  project: microservices/ProductService.Host/ProductService.Host.csproj
  bindings:
    - name: https
      port: 44344
      protocol: https
   -  name: http
      port: 5100
      protocol: http
- name: blogging
  project: microservices/BloggingService.Host/BloggingService.Host.csproj
  bindings:
    - name: https
      port: 44357
      protocol: https
    - name: http
      port: 5200
      protocol: http
```
