### ISSUE TITLE
Support env, env_file for Azure Function

### ISSUE THREAD

**Issue by GKotfis** [dotnet/tye#1161]
### What should we add or change to make your life better?

Add support for env, env_file for `azureFunction` service

### Why is this important to you?

Right now, there is no option to pass any env variables to az function.
I tried to declare it such way:
```
name: az-functions
services:
- name: my-func
  azureFunction: api/MyFunction
  env_file:
    - env_shared.env
```
but this leads to an error:
```
Drats! 'run' failed:
        Unable to determine service type.
```

Also tried with `env` - getting same error.
