### ISSUE TITLE
Is it possible to use YAML anchors in tye.yaml?

### ISSUE THREAD

**Issue by daniel-simpson** [dotnet/tye#1164]
According to external documentation [here](https://learnxinyminutes.com/docs/yaml/), the YAML format allows an anchor syntax to avoid having to repeat blocks of content multiple times.

For example, the following two tye.yaml files should be functionally equivalent according to the YAML spec:

```yaml
name: testproject

services:
  - name: myproject
    env:
      envOne: one
      envTwo: two
  - name: myotherproject
    env:
      envOne: one
      envTwo: two
```

```yaml
name: testproject

services:
  - name: myproject
    env: &commonParams
      envOne: one
      envTwo: two
  - name: myotherproject
    env:
      <<:*commonParams
```

Does Tye allow developers to use this syntax?  While it isn't a huge difference for this trivial example, it would be very useful to be able to specify shared configuration once and share amongst related services

**Comment by ikkentim** [comment]
Yes.

```yaml
name: webapptest
services:
- name: webapplication1
  project: WebApplication1/WebApplication1.csproj
  bindings:
  - name: http
    port: 5000
  env: &common_env 
    - name: envOne
      value : one
    - name: envTwo
      value: two
- name: webapplication2
  project: WebApplication2/WebApplication2.csproj
  bindings:
  - name: http
    port: 5001
  env: *common_env

```
