### ISSUE TITLE
Use a build queue to avoid file locking and optimise build time

### ISSUE THREAD

**Issue by james-allan-lloyd** [dotnet/tye#1187]
Hi there! I was running into issue #580 (specifically a shared library being built in parallel by two depending projects) so I thought I'd look into a possible solution.

My idea was to queue the requests to build to another worker task, which would then deque in batches, remove duplicate calls if necessary, and optionally look to see if the project was part of a globally configured solution - and use that to build it if so.

Example config (albeit the simplest approach):
```yaml
name: tye-build-fix
solution: tye-build-fix.sln
services:
- name: frontend
  project: frontend/frontend.csproj
- name: backend
  project: backend/backend.csproj
# both projects depend on SharedLibrary/SharedLibrary.csproj
```

I have working code (about a day's worth of work), but I saw you'd prefer discussion before PR?
