### ISSUE TITLE
Tye with prometheus

### ISSUE THREAD

**Issue by Skeferstat** [dotnet/tye#1214]
Hello, I am just about to try Tye. It is magic... 
I have Prometheus running in a Docker container.
In Visual Studio am developing an Asp.net core app. From this app I want Prometheus to collect the metrics. 
Prometheus needs the address of the app in its configuration file (prometheus.yml, target-section). And here is my problem: how to do that? 

Here is my tye.yml:

```
name: cutter
services:

- name: cutter
  project: Cutter.csproj
  
- name: prometheus
  image: prom/prometheus
  bindings:
    - containerPort: 9090
  volumes:
    - source: ./prometheus.yml
      target: /etc/prometheus/prometheus.yml
```

And here is the prometheus.yml:

```
global:
  scrape_interval: 5s 

scrape_configs:
  
  - job_name: 'cutter
    scheme: http
    static_configs:
      - targets: ['??????????????']         <================     
    metrics_path: /metrics-text
```

Thanks for the explanation and help!

**Comment by philliphoff** [comment]
@Skeferstat I'm not familiar with Prometheus, so take this all with a grain of salt.  Looking through the GitHub repo issues, it looks like dynamic hosts for `scrape_configs` has been an issue in general for a while and is not limited to Tye.  It appears that one common workaround is to change the entrypoint for the Prometheus container and run a script that generates a configuration file based on a template before running Prometheus itself.

Tye allows you to attach volumes to containers, which you could use to supply the configuration template and the generation script.  Tye also provides all of the host/port information to the container via environment variables which could be used by that script to generate the configuration file from that template.  I think that's where I'd start, anyway.

**Comment by philliphoff** [comment]
@Skeferstat Let us know if you were able to were able to make any progress.

**Comment by Skeferstat** [comment]
Hi,
I don't know how to do it. That's why I'm hoping for help...

**Comment by ismaelhamed** [comment]
Maybe executables and containers don't share the same network in Tye? I can easily scrape other containers by using the service `name` as hostname, but not executables:

tye.yml
```
name: demo
services:

- name: cutter
  project: Cutter.csproj
  bindings:
    - port: 9182
  
- name: prometheus
  image: prom/prometheus
  bindings:
    - port: 9090
  volumes:
    - source: ./prometheus.yml
      target: /etc/prometheus/prometheus.yml
      
- name:  otel-collector
  image: otel/opentelemetry-collector:0.54.0
  args: "--config=/etc/otel-collector-config.yml"
  volumes:
    - source: ./otel-collector-config.yml
      target: /etc/otel-collector-config.yml
  bindings:
    - port: 4317
      name: otel-collector4317
    - port: 8888
      name: otel-collector8888
    - port: 8889
      name: otel-collector8889      
```
prometheus.yml
```
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  

  - job_name: 'opentelemetry'
    static_configs:
      - targets: ['otel-collector:8888', 'otel-collector:8889']  <============= this works!!

  - job_name: 'cutter'
    static_configs:
      - targets: ['cutter:9182']  <============= this doesn't. 
```
