### ISSUE TITLE
Azure Functions V3 with TargetFramework 5.0 and Worker Runtime dotnet-isolated aren't supported

### ISSUE THREAD

**Issue by hirensharma** [dotnet/tye#1236]
### Describe the bug
I have a couple of micro-services along with some Azure Functions (dotnet-isolated ones) and the Azure Function fails to run. I guess the command its using internally is dotnet run, whereas, the new function utilizes the command "func start" with the help of Azure Function Core Tools

### Further technical details

- Tye version: 0.10.0 on windows

**Comment by fleed** [comment]
Same problem here. Any temp workarounds?

**Comment by fleed** [comment]
I found a workaround using the following configuration:

```yaml
- name: myfunc
  executable: func
  args: start {pathtofolder}/Company.FunctionApp1.csproj -p 7071
  workingDirectory: {pathtofolder}
  bindings:
    - port: 7071
      protocol: http
```

Anyway there might be a much simpler solution, so still open for suggestions
