### ISSUE TITLE
Dapr extension services block is not recognized

### ISSUE THREAD

**Issue by chan4lk** [dotnet/tye#1238]
### Describe the bug
I want to specify the metrics port for each service in dapr extension area. But when its included according to the schema it throws an exception.

### To Reproduce
1. Add following lines to the `tye.yaml`.
```yaml
extensions:
  - name: dapr
    components-path: ./components/tye
    config: config
    services:
     identityapi:
        metrics-port: 9093
```
2. Run command `tye run`
3. An Exception is thrown.
```shell
Loading Application Details...
Error parsing tye.yaml: (8, 5): Expected scalar value for key: "services".
```

### Further technical details
1. tye --version output
```
0.10.0-alpha.21420.1+7cec0655cc474aee8d3c3a3d180678985209d439
```
2. Debug output
```shell
Loading Application Details...
Error parsing tye.yaml: (8, 7): Expected scalar value for key: "services".
```
3. Platform - Windows
