### ISSUE TITLE
Unable to get connection string for `redislabs/rejson`

### ISSUE THREAD

**Issue by spicycoder** [dotnet/tye#1271]
### Describe the bug
Unable to get connection string for `redislabs/rejson`

### To Reproduce

I am using `tye` with ASP.NET 6.0 Web API
Redis as data store, using [Redis OM](https://github.com/redis/redis-om-dotnet)

```yaml
name: superHeroes
services:
  - name: bookofheroes
    project: BookOfHeroes/BookOfHeroes.csproj
  - name: redis
    image: redislabs/rejson
    bindings:
      - port: 6500
        name: redis
        connectionString: "${host}:${port}"
    tags:
      - redis
  - name: redis-cli
    image: redislabs/rejson
    args: "redis-cli -h redis MONITOR"
    tags:
      - redis
```

##### Program.cs

```cs
builder.Services.AddSingleton(_ =>
    new RedisConnectionProvider(builder.Configuration.GetConnectionString("redis", "redis")));
```

###### Indexing

```cs
var redisConnectionProvider = app.Services.GetService<RedisConnectionProvider>();
redisConnectionProvider?.Connection.CreateIndex(typeof(Hero));
```

#### Logs

```
[bookofheroes_bd998273-3]:C:\Projects\try-redis\BookOfHeroes\bin\Debug\net6.0\BookOfHeroes.exe
[bookofheroes_bd998273-3]: Unhandled exception. StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: FT.CREATE; UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 2s ago, v: 2.2.50.36290, mc: 1/1/0, mgr: 10 of 10 available, clientName: MATRIXEAN-PC, IOCP: (Busy=0,Free=1000,Min=12,Max=1000), WORKER: (Busy=0,Free=32767,Min=12,Max=32767), v: 2.2.50.36290
[bookofheroes_bd998273-3]: ---> StackExchange.Redis.RedisConnectionException: UnableToConnect on localhost:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 2s ago, last-write: 2s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 2s ago, v: 2.2.50.36290
[bookofheroes_bd998273-3]: --- End of inner exception stack trace ---
[bookofheroes_bd998273-3]: at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2837
[bookofheroes_bd998273-3]: at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
[bookofheroes_bd998273-3]: at StackExchange.Redis.RedisDatabase.Execute(String command, ICollection`1 args, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1203
[bookofheroes_bd998273-3]: at StackExchange.Redis.RedisDatabase.Execute(String command, Object[] args) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1199
[bookofheroes_bd998273-3]: at Redis.OM.RedisConnection.Execute(String command, String[] args)
[bookofheroes_bd998273-3]: at Redis.OM.RediSearchCommands.CreateIndex(IRedisConnection connection, Type type)
[bookofheroes_bd998273-3]: at Program.<Main>$(String[] args) in C:\Projects\try-redis\BookOfHeroes\Program.cs:line 19
```

### Further technical details

- tye version: `0.10.0-alpha.21420.1+7cec0655cc474aee8d3c3a3d180678985209d439`
- ASP.NET 6.0 - Web API
- Platform: Windows

> Note:

If I use an invalid connection string name, and change the port to `6379`, it'll work fine

Because, connection string will be null, hence it'll try to connect to default redis connection at `6379`

Related: https://github.com/redis/redis-om-dotnet/issues/45
