### ISSUE TITLE
Bind to something else then localhost doesn't work

### ISSUE THREAD

**Issue by remcoros** [dotnet/tye#1277]
### Describe the bug

I'm trying to bind my ASP.Net core application to a custom hostname. The main reason being that I want to investigate http calls with Fiddler, which cannot capture traffic from 'localhost', but it can if I use another loopback interface or my machine name.

According to the docs, 'bindings' has a 'host' element that can be used to specify a hostname. I'd expect that tye respects this and generates a correct ASPNETCORE_URLS environment variable.

Whatever I try though, it always listens on localhost:5019.
- Tried using the 'host' element of bindings
- Tried specifying the custom urls in launchsettings.json
- Tried adding ASPNETCORE_URLS as an 'env:' variable in tye.yaml. But this seems to get overriden.

How can I specify a custom host name that tye respects and creates the correct ASPNETCORE_URLS?

### To Reproduce

```
services:
- name: my-service
  project: src\MyWebApp\MyWebApp.csproj
  bindings:
    - name: http
      protocol: http
      host: raider
      port: 5019
```

'raider' is my machine name in this case.

### Further technical details

tye version 0.10.0-alpha.21420.1+7cec0655cc474aee8d3c3a3d180678985209d439 on Windows 10
