### ISSUE TITLE
Allow environment variables in project path

### ISSUE THREAD

**Issue by martinstenhoff** [dotnet/tye#1292]
We have a ton of services across multiple repos with a "tye project" in yet another repo to be able to run all our services locally.

I want to be able to use an environment variable to define the base path to a project in tye.yaml
```
name: ThePlatform
services:
- name: frontend-b
  project: ${FRONTEND_A_HOME}/src/Company.FrontEndA/Company.FrontEndA.csproj
...
- name: frontend-b
  project: ${FRONTEND_B_HOME}/src/Company.FrontEndB/Company.FrontEndB.csproj
...
```

I've tried both the above syntax and the following:
*  $(FRONTEND_A_HOME)
* %FRONTEND_A_HOME%

but it seems like tye won't expand environment variables in project paths (or I am using the wrong syntax).

Is there support for env variable expansion in project path, as I'd like to avoid dictating the checkout structure relative to the Tye project for all "services" if possible?
