### ISSUE TITLE
Azure Functions configuration add duplicate port at command line

### ISSUE THREAD

**Issue by jp1482** [dotnet/tye#1316]
### To Reproduce
Use following file for configuration.
```
name: myservices
services:
- name: customerservice
  azureFunction: customerservice/
  args: --port 7071
- name: orderservice
  azureFunction: orderservice/
  args: --port 7072
```

### Further technical details

- Version: 0.11.0-alpha.22111.1+3edef5428949c518c078844d6438e5ba86fce600
- Windows

Instead of args if I use bindings then it works.
```
name: myservices
services:
- name: customerservice
  azureFunction: customerservice/
  bindings:
   - port: 7071
- name: orderservice
  azureFunction: orderservice/
  bindings:
   - port: 7072
```
Working example with binding is at : https://github.com/jp1482/MultipleFunctionApps. If you update file with content in reproduce step then it is problem.
