### ISSUE TITLE
Add flag to disable / ignore service in tye application

### ISSUE THREAD

**Issue by Robbss** [dotnet/tye#1340]
I would like to be able to set a flag that determines whether a service should be run when the Tye application is started.

Example:
```
name: example-app
services:
  - name: service-a
    enabled: false
    ...
  - name: service-b
    enabled: true
    ...
```

Our team manages and develops a lot services, each with varying dependencies on other services. We have one big tye.yaml that includes all applications and their configuration.

It's very heavy to run all of our services at once, so currently we comment / uncomment services to specify the required services for our current task, which is just annoying manual labour.

If a flag was added it'd be much easier to develop additional tooling that'd allow us to automate a large part of our issue.

I'm currently working on a PR that would add this feature (with `enabled` implicitly true), is this an addition that would be welcome?
