### ISSUE TITLE
How to improve start-up time

### ISSUE THREAD

**Issue by jkears** [dotnet/tye#1343]
I love Tye.  It's absolutely perfect for spinning up apps and services that need to connect with other. 

That said, there is one area that I can't seem to improve upon and that is over-all startup time for all services,  

It seems in my environment that it takes approximate **7-8 seconds** per service to fully stand-up the set of services.

This is an accumulative time.  For example, if I start only 4 services it takes ~ 28 seconds to start however if I have 21 services it takes ~ 170 seconds to start up all 21 services.

I would like to reduce the time spent waiting for these services to stand up via Tye however I do not see any logging within the startup period so I am at a loss to understand where to look to improve this time. 

Are there any techniques that can be applied to reduce the over-all start-up time?  Is this delay due to Docker?  

Any assistance would be greatly appreciated. 

Cheers

**Comment by Phiph** [comment]
Hi jkears,

that sounds interesting, can you share an example of your tye.yaml file please? 

I'd like to understand if the services you are defining are csproj or Dockerfiles etc. 

Thanks in advance

**Comment by jkears** [comment]
@Phiph 

These are used as csproj services...
Here is an example Tye file from another project with 6 services ...


```
name: nextware-domain
extensions:
- name: dapr
  log-level: debug
  components-path: ./components/
services:
- name: nextware-domain-gw
  project: GateWay/NextWare.Domain.GraphQLGateWay.csproj
  external: false
  replicas: 1
  build: false
  bindings:
  - protocol: https
    port: 6241
- name: nextwaredomainauthorizationservices
  project: BoundedContexts/AuthorizationServices/API/NextWare.Domain.AuthorizationServices.API.csproj
  external: false
  replicas: 1
  build: false
- name: nextwaredomainmetaservices
  project: BoundedContexts/MetaServices/API/NextWare.Domain.MetaServices.API.csproj
  external: false
  replicas: 1
  build: false
  bindings:
  - protocol: https
    port: 6231
- name: nextwaredomainrulesservices
  project: BoundedContexts/RulesServices/API/NextWare.Domain.RulesServices.API.csproj
  external: false
  replicas: 1
  build: false
  bindings:
  - protocol: https
    port: 6233
- name: nextwaredomainvalidationservices
  project: BoundedContexts/ValidationServices/API/NextWare.Domain.ValidationServices.API.csproj
  external: false
  replicas: 1
  build: false
  bindings:
  - protocol: https
    port: 6235
- name: nextwaredomainreactionpolicyservices
  project: BoundedContexts/ReactionPolicyServices/API/NextWare.Domain.ReactionPolicyServices.API.csproj
  external: false
  replicas: 1
  build: false
  bindings:
  - protocol: https
    port: 6237
- name: nextwaredomainresourceservices
  project: BoundedContexts/ResourceServices/API/NextWare.Domain.ResourceServices.API.csproj
  external: false
  replicas: 1
  build: false
  bindings:
  - protocol: https
    port: 6239
```
