### ISSUE TITLE
Service replicas load balancing

### ISSUE THREAD

**Issue by andrei-micuda** [dotnet/tye#1379]
Hello!

I wanted to test a service with 2 replicas within tye in order to see how load balancing works between them.

I was using a config similar to the following:

```yaml
name: load-balancing-test
services:
- name: app-a
  project: ApplicationA/ApplicationA.csproj
  bindings:
  - port: 5070
  replicas: 2
```

And withing the `Startup.cs` file of the application I've made an endpoint that returns the value of the current app instance using the `APP_INSTANCE` env variable, similar to the ingress sample.

```c#
endpoints.MapGet("/test-tye", async context =>
{
    var instance = Environment.GetEnvironmentVariable("APP_INSTANCE") ?? Environment.GetEnvironmentVariable("HOSTNAME");
    var text = 
        "Hello from Application A " + instance + Environment.NewLine +
        "Path is: " + context.Request.Path;
    await context.Response.WriteAsync(text);
});
```

When launching tye, even though within the dashboard I see the 2 replicas up and running, when navigating to the endpoint (`localhost:5070/test-tye`), I always get the same app instance back.
Tried testing from various browsers, incognito mode etc. I always end up getting the same instance.

Am I misinterpreting the way replicas work?
