### ISSUE TITLE
Run multiple application on different ports in ingress container.

### ISSUE THREAD

**Issue by imranknp** [dotnet/tye#1386]
Hello,

I deployed the sample project of ingress configuration in azure Kubernetes with the below configuration.

```
ingress:
  - name: ingress
    bindings:
      - port: 8080
    rules:
      - path: /A
        service: app-a
      - path: /B
        service: app-b
      - host: a.example.com
        service: app-a
      - host: b.example.com
        service: app-b
```

I can run the project by assigned IP addresse with the given path of applications A and B. 

http://{IPAddress}/A and http://{IPAddress}/B

Can we assign the different ports in the ingress container to expose both applications?

Like 
Application A:  http://{IPAddress}:44354
Application B:  http://{IPAddress}:44355
