### ISSUE TITLE
Tye with dapr on .net 6 - DAPR_HTTP_PORT not set DAPR_GRPC_PORT

### ISSUE THREAD

**Issue by penfold** [dotnet/tye#1429]
### Describe the bug

DAPR_HTTP_PORT and DAPR_GRPC_PORT are not being automatically set in for the dotnet process when using tye with dapr.

Executing the same  dapr run call from the same Powershell terminal works correctly,

### To Reproduce

Create a simple  .net 6 console app with the following code in program.cs:
```
while (true)
{
    Console.WriteLine("DAPR_HTTP_PORT:" + Environment.GetEnvironmentVariable("DAPR_HTTP_PORT"));
    Console.WriteLine("DAPR_GRPC_PORT:" + Environment.GetEnvironmentVariable("DAPR_GRPC_PORT"));
    await Task.Delay(1000);
}
```
Call using dapr:
 dapr run --app-id testinvoker --app-protocol http --dapr-http-port 3501 -- dotnet run

Gives output:
== APP == DAPR_HTTP_PORT:3501
== APP == DAPR_GRPC_PORT:62501
== APP == DAPR_HTTP_PORT:3501
== APP == DAPR_GRPC_PORT:62501

But using tye.yaml:
```
name: containers
extensions:

  # Configuration for dapr goes here.
- name: dapr
  log-level: trace
  components-path: ./components/
  
# Services to run go here.
services:
  
- name: testinvoker
  project: TestInvoker/TestInvoker.csproj
```

Looking in the logs on Tye dashboard, you see:
[testinvoker_6c08ff03-5]: DAPR_HTTP_PORT:
[testinvoker_6c08ff03-5]: DAPR_GRPC_PORT:
[testinvoker_6c08ff03-5]: DAPR_HTTP_PORT:
[testinvoker_6c08ff03-5]: DAPR_GRPC_PORT:

This all means that the DaprClientBuilder creates a DaperClient with wrong/default ports.
  

### Further technical details

tye --version
0.11.0-alpha.22111.1+3edef5428949c518c078844d6438e5ba86fce600

dapr --version
CLI version: 1.7.1
Runtime version: 1.7.4

This is all run in a Powershell terminal on Windows 11.

Have I got something obviously wrong somewhere or is this a bug with my tye.yaml?

**Comment by penfold** [comment]
I've debugged through this the issue is in: DaprExtension:53-57

  ```
if (httpBinding == null && (serviceConfiguration?.Enabled == null || !serviceConfiguration.Enabled.Value))
  {
      context.Output.WriteDebugLine($"Dapr has been disabled for unbound service {project.Name}.");
      continue;
  }
```

This is making the assumption that service that is not itself and endpoint service does not need to have a dapr sidecar.

I jumped over this clause and the problem is resolved.

**Comment by penfold** [comment]
Could this be solved in an extensible way by having a extension child to the service node in the tye yaml.

e.g.

services:
  
- name: testinvoker
  project: TestInvoker/TestInvoker.csproj
  extensions:
  - dapr:
    - enable: true

This way we can have per extension specific config for each service. In this case, it would simply trigger the sidecar to be added.

**Comment by penfold** [comment]
Or is this already available via `serviceConfiguration.Enabled` ?

If so, what is the yaml syntax?

**Comment by penfold** [comment]
Found it:

see the schema https://github.com/dotnet/tye/blob/main/docs/reference/schema.md looking for Enabled.

the syntax is:

```
name: containers
extensions:

  # Configuration for dapr goes here.
- name: dapr
  log-level: trace
  components-path: ./components/
  services:
    testinvoker:
        enabled: true
  
# Services to run go here.
services:
  
- name: testinvoker
  project: TestInvoker/TestInvoker.csproj
```
