### ISSUE TITLE
Dapr extension not considering Azure function apps

### ISSUE THREAD

**Issue by maltegoetz** [dotnet/tye#1431]
### Describe the bug
When setting up a tye.yaml with an Azure function app and the dapr extension, there is no sidecar started. 

### To Reproduce
1. Create a new function app in an empty folder called `sample-app`.
2. Initialize tye and change the tye.yaml contents to the following:
```
name: sample-name

extensions:
- name: dapr
  log-level: debug
  components-path: dapr-components/

services:
# - name: sample-app
#   azureFunction: sample-app/
```
3. Add a folder `dapr-components` to your root folder and optionally place configuration specs for dapr in there.
4. Use `tye run` to start tye and note that there is no dapr sidecar started for the azure function project.

### Further technical details

$ tye --version --> 0.11.0-alpha.22111.1+3edef5428949c518c078844d6438e5ba86fce600
If I understand correctly, Azure function projects are ignored in the Dapr Extensions: https://github.com/dotnet/tye/blob/5b3d7f611da03b5133e1c5e048cf59e6c9ba46d4/src/Microsoft.Tye.Extensions/Dapr/DaprExtension.cs#L29
