### ISSUE TITLE
MongoDB with volumes fails to start the second time

### ISSUE THREAD

**Issue by esskar** [dotnet/tye#1440]
### Describe the bug
I added MongoDB with volumes to my `tye.yaml`. The first time it starts, the database just fine and the volume folder is created. When I stop and start tye again, mongo fails with

```
"t":{"$date":"2022-08-19T20:01:55.311+00:00"},"s":"W",  "c":"STORAGE",  "id":22347,   "ctx":"initandlisten","msg":"Failed to start up WiredTiger under any compatibility version. This may be due to an unsupported upgrade or downgrade."}
{"t":{"$date":"2022-08-19T20:01:55.311+00:00"},"s":"F",  "c":"STORAGE",  "id":28595,   "ctx":"initandlisten","msg":"Terminating.","attr":{"reason":"1: Operation not permitted"}}
{"t":{"$date":"2022-08-19T20:01:55.311+00:00"},"s":"F",  "c":"-",        "id":23091,   "ctx":"initandlisten","msg":"Fatal assertion","attr":{"msgid":28595,"file":"src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp","line":687}}
{"t":{"$date":"2022-08-19T20:01:55.311+00:00"},"s":"F",  "c":"-",        "id":23092,   "ctx":"initandlisten","msg":"\n\n***aborting after fassert() failure\n\n"}
```  

### To Reproduce

My `tye.yaml` for reference

```yaml
# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
# define global settings here
name: my.project # application name
registry: myproject # dockerhub username or container registry hostname

# define multiple services here
services:
  - name: api
    project: my.project/my.project.csproj
    # executable: app.exe # path to an executable (relative to this file)
    # args: --arg1=3 # arguments to pass to the process
    # replicas: 5 # number of times to launch the application
    # env: # array of environment variables
    #  - name: key
    #    value: value
    # bindings: # optional array of bindings (ports, connection strings)
    # - port: 8080 # number port of the binding
  - name: mongo
    image: mongo
    env:
      - name: ME_CONFIG_MONGODB_ADMINUSERNAME
        value: root
      - name: ME_CONFIG_MONGODB_ADMINPASSWORD
        value: example
    bindings:
      - port: 27017
        connectionString: 'mongodb://${host}:${port}'
    volumes:
      - source: ./.volumes/mongo/data
        target: /data/db
  - name: mongo-express
    image: mongo-express
    env:
      - name: ME_CONFIG_MONGODB_ADMINUSERNAME
        value: root
      - name: ME_CONFIG_MONGODB_ADMINPASSWORD
        value: example
    bindings:
      - port: 8081
        containerPort: 8081
        protocol: http
  - name: redis
    image: redis
    bindings:
      - port: 6379
        connectionString: '${host}:${port}'
  - name: redis-cli
    image: redis
    args: 'redis-cli -h redis MONITOR'
``` 

### Further technical details

Running tye on mac

```
tye --version                                                                                                                      
0.11.0-alpha.22111.1+3edef5428949c518c078844d6438e5ba86fce600
```
