### ISSUE TITLE
Is there a way to set the APP_API_TOKEN environment variable for dapr in tye.yaml?

### ISSUE THREAD

**Issue by JasonRodman** [dotnet/tye#1442]
I am trying to enable dapr to app token security while running in tye, but running into some roadblocks. The dapr [documentation](https://docs.dapr.io/operations/security/app-api-token/)  says to set that environment variable when running in self-hosted mode, but I have not found a way to do that when loading it as an extension in tye.yaml. What would be the recommended way to set this for all apps launched by tye with dapr?

**Comment by davidfowl** [comment]
Sounds like we'd need a way to pass this via an argument in the dapr extension

**Comment by onionhammer** [comment]
Just came across this too.. perhaps it could be picking up an environment variable

```yaml
name: my-proj
  project: src/MyProj.csproj
  env:
    - name: APP_API_TOKEN
      value: local
  bindings:
    - port: 5053
```
