### ISSUE TITLE
How to overwrite ASPNETCORE_ENVIRONMENT when running in Docker?

### ISSUE THREAD

**Issue by josdeweger** [dotnet/tye#1476]
I have a bunch of appsetting json files for different environments, like for instance appsettings.local.json. I'm loading the environment specific file like this:
`config.AddJsonFile($"appsettings.{hostingContext.HostingEnvironment.EnvironmentName}.json", optional: false, reloadOnChange: true);`

In my yaml file I set 
```
name: MyServices
services:
  - name: SomeApi
    project: SomeApi/SomeApi.csproj
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: "local"
```

When running `tye run` this is fine, but using `--docker` seems to overwrite the env variable with "Development". I can see this in the logs as wel, where I can see `-e "ASPNETCORE_ENVIRONMENT=Development"` being passed on container initialization. 

How can I set ASPNETCORE_ENVIRONMENT to the value I want?
