### ISSUE TITLE
Add ability to use network aliases 

### ISSUE THREAD

**Issue by dziedrius** [dotnet/tye#1492]
### What should we add or change to make your life better?
Docker compose has ability to add network aliases like this:
```
tests.mock.proxy:
    container_name: tests.mock.proxy
    image: nginx
    networks:
      default:
        aliases:
          - api.to-be.mocked.com
          - orders.local.domain.com
```
meaning, that I can access my services by DNS names - which might serve at least couple purposes:
- I can have url's using similar schema to ones in production.
- I can mock third party services, if their official clients do not support using different uri and need valid ssl certificates.
- Single container might handle requests from multiple host names.

### Why is this important to you?
Currently we have two configs - docker-compose and tye just because we can't fully control host names in tye and we need that for our integration tests, as we need to mock out several third party APIs.
