### ISSUE TITLE
# Configure --app-max-concurrency for the orders service not working

### ISSUE THREAD

**Issue by makhele** [dotnet/tye#1500]
### Describe the bug
As stated in the [docs ](https://github.com/dotnet/tye/blob/main/docs/recipes/dapr.md) you can # Configure --app-max-concurrency for the orders service

but when I try on my `tye.yaml` file I get the following error message:
```
Error parsing tye.yaml: (23, 7): Expected scalar value for key: "services".
```

### Further technical details

- `tye --version: 0.10.0-alpha.21420.1+7cec0655cc474aee8d3c3a3d180678985209d439`
- If possible rerun the command with `-v debug` and include the output
- Platform: Windows 11

**Comment by davidfowl** [comment]
Where is your tye.yaml?

**Comment by makhele** [comment]
As per the docs
```
# Configure --app-max-concurrency for the orders service
extensions:
- name: dapr
  services:
    orders:
      app-max-concurrency: 1
services:
- name: orders
  project: orders/orders.csproj
- name: products
  project: products/products.csproj
- name: store
  project: store/store.csproj
```

**Comment by makhele** [comment]
> Where is your tye.yaml?

Same as the docs

```
# Configure --app-max-concurrency for the orders service
extensions:
- name: dapr
  services:
    orders:
      app-max-concurrency: 1
services:
- name: orders
  project: orders/orders.csproj
- name: products
  project: products/products.csproj
- name: store
  project: store/store.csproj
```
