### ISSUE TITLE
Tye deploy, ingress issue

### ISSUE THREAD

**Issue by mpp** [dotnet/tye#1572]
Hi!

I'm starting with kubernetes (I know a very little) and tye.
I get no ingress rules when running `tye deploy`

tye.yml:
```yaml
name: kubernetes-test
ingress:
  - name: date-ingress
    bindings:
      - port: 8080
        protocol: http
        ip: "*"
    rules:
      - path: /Date
        preservePath: true
        service: date-service
registry: localhost:32000
services:
- name: date-service
  project: /KubeTest/KubeTest.csproj
```

```
$ kubectl get ingress -A
NAMESPACE   NAME           CLASS    HOSTS   ADDRESS   PORTS   AGE
default     date-ingress   <none>   *                 80      2m16s
```

Am I missing something or this is not supported (https://github.com/dotnet/tye/blob/main/docs/tutorials/hello-tye/01_deploy.md)?
Thanks in advance!
