### ISSUE TITLE
esproj support

### ISSUE THREAD

**Issue by rolfik-mycronic** [dotnet/tye#1607]
Could esproj javascript projects be supported in service project value of tye.yaml?

We have backend csproj services which work fine with tye.

We have also UI vue frontends.
It would be nice to execute the whole system with tye.
To do it we would just add vue esproj services like `project: ui.esproj`.
I can add them now with executable service types:

```
services:
- name: ui
  executable: '%PROGRAMFILES%\nodejs\npm.cmd'
  args: run serve -- --port #
  bindings:
  - port: #
    protocol: http
```

Executable with args is also defined in esproj:

```
<Project Sdk="Microsoft.VisualStudio.JavaScript.Sdk/0.5.83-alpha">
  <PropertyGroup>
    <StartupCommand>npm run serve -- --port #</StartupCommand>
    <JavaScriptTestRoot>.\</JavaScriptTestRoot>
    <JavaScriptTestFramework>Jest</JavaScriptTestFramework>
    <!-- Command to run on project build -->
    <BuildCommand>
    </BuildCommand>
    <!-- Command to create an optimized build of the project that's ready for publishing -->
    <ProductionBuildCommand>npm run build</ProductionBuildCommand>
    <!-- Folder where production build objects will be placed -->
    <BuildOutputFolder>$(MSBuildProjectDirectory)\dist</BuildOutputFolder>
  </PropertyGroup>
</Project>
```

We use tye only for development and docker compose for deployment.

Thank You
