### ISSUE TITLE
First class support for running azure functions for local dev

### ISSUE THREAD

**Issue by davidfowl** [dotnet/tye#18]
Microservices may consist of apps and functions (and other executables) see what it takes to launch the functions runtime as part of the microservice topology.

**Comment by luisgizirian** [comment]
It'd be lovely to have this packed into the tool. The Micronetes time suggestion (https://github.com/davidfowl/Micronetes/issues/8).

**Comment by timjroberts** [comment]
This would be awesome. We're currently defining services like this to spin up Functions Apps:
```
services:
- name: web
  executable: dotnet
  args: C:/Users/timroberts/AppData/Roaming/npm/node_modules/azure-functions-core-tools/bin/func.dll host start --prefix ./bin/Debug/netcoreapp3.1  --port 8080
  workingDirectory: ./src/WebGatewayService
  bindings:
  - port: 8080
    protocol: http
```
At the moment, it appears that `args` can't expand environment variables? It would be nice to replace the hard coded path with something that referenced HOME.

**Comment by jkotalik** [comment]
Yeah I currently have that effectively working locally right now, however there are a few challenges I'm hitting:
- Installing func.exe/func.dll. Right now, the func.exe you have is installed via NPM usually and not on the path by default (I tried just calling func.exe on windows and that failed). VS also installs func to a different location as well. I think in tye, we may need to install func locally based on OS and version rather than trying to find one; writing logic to find func.exe never is easy and can cause misconceptions.
- Deploying. Functions can be deployed to both k8s and azure, and ideally we'd like as much as possible to work there.
- Service discovery. This one is currently hard, especially for things like queues. Binding information for functions is usually defined in attributes above a function. 

> At the moment, it appears that args can't expand environment variables? It would be nice to replace the hard coded path with something that referenced HOME.

Yeah this may not work for args, I think it may work for env though. We'll look into it.

**Comment by timjroberts** [comment]
This is working great for local @jkotalik 
Changed my tye.yaml (from above) to:
```
services:
- name: web
  azureFunction: src/WebGatewayService/bin/Debug/netcoreapp3.1
  bindings:
  - port: 8080
    protocol: http
```
and all working!

Any plans to look at the deployment side?
