### ISSUE TITLE
Kubernetes secrets as EnvVars

### ISSUE THREAD

**Issue by unaizorrilla** [dotnet/tye#185]
### What should we add or change to make your life better?

At this moment, Tye is creating secrets and mounting them as a volumes on k8s deployments. However this secret is not referenced as an env var. K8S allow to that with something like

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
  restartPolicy: Never

```

### Why is this important to you?

Using secrets as currently deployed enforces us to add a new configuration provider, KeyPerFile, and to split our code to read configuration keys differently  when is executed on **tye run** and when is deployed to **k8s**.

 

```csharp
           services.AddStackExchangeRedisCache(options =>
            {
                var connectionString = Configuration["connectionstring:redis"];
                if (connectionString != null)
                {
                    options.Configuration = connectionString;
                }
                else
                {
                    options.Configuration = $"{Configuration["service:redis:host"]}:{Configuration["service:redis:port"]}";
                }
            });
```
