### ISSUE TITLE
Add heathcheck support

### ISSUE THREAD

**Issue by davidfowl** [dotnet/tye#19]
We should add health checking support to the host to know if a service is running properly.

**Comment by areller** [comment]
@davidfowl I've experimented with it a bit and I have something in this branch https://github.com/areller/tye/tree/replica-health

Basically, you can define a `health` field in the service description that can be configured with these arguments

* endpoint (The http endpoint that will be checked every interval for HTTP 2xx)
* testInterval (The interval of the testing in seconds, default: 1)
* gracePeriod (After a replica became sick, how many seconds to wait until we kill the replica, default: 5)
* bootPeriod (After a replica has started, how many seconds to wait for it to become healthy before killing it, default: 5)

Here is an example yaml

```
# tye application configuration file
# read all about it at https://github.com/dotnet/tye
name: single-project-health
services:
- name: test-project
  project: test-project/test-project.csproj
  bindings:
    - port: 8081
  health:
    endpoint: /health
```

(Replicas of services without the `health` field will automatically become healthy upon creation)

The heart of this feature is in this file (and line)
https://github.com/areller/tye/blob/94e123bf9b0f3c01269cf5881aacf539b2517a85/src/Microsoft.Tye.Hosting/Hospital.cs#L135

This can be improved by

* Adding another state, readiness (a replica can be healthy but not ready, in that case, we don't kill it)
* Displaying health status/statistics in the dashboard

Once you have healthcheck (and maybe readiness) you can start talking about more advanced concepts like dependencies.
