### ISSUE TITLE
Align with docker compose format?

### ISSUE THREAD

**Issue by davidfowl** [dotnet/tye#190]
Should we make it trivial to convert a docker compose file to the tye.yaml.

```yaml
version: '3.2'
services:
  config:
    image: "steeltoeoss/configserver:1.3.2"
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
      - type: bind
        source: ./src/config
        target: /config
    ports:
      - "8888:8888"
  eureka:
    image: "steeltoeoss/eurekaserver:1.4.4"
    ports:
      - "8761:8761"
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: steeltoe
      MYSQL_DATABASE: steeltoe
      MYSQL_USER: steeltoe
      MYSQL_PASSWORD: steeltoe
```

Today the equivalent tye.yam looks like this:

```yml
services:
  - name: config:
    image: "steeltoeoss/configserver:1.3.2"
    args: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
        - source: ./src/config
          target: /config
    bindings:
      - port: 8888
  - name: eureka:
    image: "steeltoeoss/eurekaserver:1.4.4"
    bindings:
      - port: 8761
  mysql:
    image: "mysql:5.7"
    bindings:
      - port: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
         value: steeltoe
      - name: MYSQL_DATABASE
         value: steeltoe
      - name: MYSQL_USER
         value: steeltoe
      - name: MYSQL_PASSWORD
         value: steeltoe

```

**Comment by rynowak** [comment]
Yeah, I agree on the things that are cosmetic. I'm really not a fan of the `9000:8000` syntax for ports. It makes sense for a CLI and for a configuration format.

I don't think we can align on how bindings work in tye vs ports in docker-compose. Bindings are more data-rich than ports. You can't convert back.

**Comment by davidfowl** [comment]
> Yeah, I agree on the things that are cosmetic. I'm really not a fan of the 9000:8000 syntax for ports. It makes sense for a CLI and for not for a configuration format.

Agree, I dislke the port syntax. To make this more concrete, do we like the list of services being a list of should it be a map? It leads to more nesting:

```yml
services:
  config:
    - image: "steeltoeoss/configserver:1.3.2"
      args: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
      volumes:
        - source: ./src/config
           target: /config
      bindings:
        - port: 8888
```

`command` vs `args` - Args is used for both process and container.

`env` vs `environment` - One is less typing but I'm ambivalent. The keys need to be more complex than a map because we want to support secrets.

**Comment by rynowak** [comment]
> To make this more concrete, do we like the list of services being a list of should it be a map?
> command vs args - Args is used for both process and container.

To me these are definitely cosmetic details - they are not small decisions we need to make they are part of a single big decision - *do we want to align with compose or not*.

I'm less worried about the obvious stuff like do use mappings or an array. Using mappings btw works well when the `name` is required, and doesn't work at all when the name is optional. 

I'm more worried about the true impedance mismatches we would have with docker compose. Today we default to single-phase Docker builds. If you assume we wanted to make it easy to use compose - one of two possibilities exist:

- We provide a *convert* feature and build the images as part of it
- We provide a way to generate two-phase Dockerfiles as part of it

Docker compose either requires images or Dockerfiles, so we have to do one of those things to make it easy 😆 

---

So let's step back a moment - what do we want out of aligning with compose? You said you want to make it trivial to convert - why? What's the scenario?

One idea in my brain is that we could generate a docker-compose. That's pretty trivial, and it doesn't impose a lot of constraints on us. It might be premature to try and design this feature given that we haven't exposed any ways the user can configure Docker build with tye today.

**Comment by bravecobra** [comment]
Lots of people already have docker-compose file. Deriving `tye.yml` from this extra information might be useful to get started quickly. That doesn't mean that they should follow the same syntax exactly. So if `tye init` would take `docker-compose.yml` into account to add services like database services, port configuration and existing env variables, that would be awesome. Maybe specify an existing docker-compose at the init commandline?

**Comment by NileshGule** [comment]
It would be good to have the ability to migrate an existing docker-compose file to Tye format.

**Comment by GeraudFabien** [comment]
Maybe tye could work like a appsetting.json file :
docker-compose.yml
```yaml
version: '3.2'
services:
  config:
    image: "steeltoeoss/configserver:1.3.2"
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
      - type: bind
        source: ./src/config
        target: /config
    ports:
      - "8888:8888"
  eureka:
    image: "steeltoeoss/eurekaserver:1.4.4"
    ports:
      - "8761:8761"
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: steeltoe
      MYSQL_DATABASE: steeltoe
      MYSQL_USER: steeltoe
      MYSQL_PASSWORD: steeltoe
  myaspapp:
    image: "myapps/myaspapp"
```
(note: i added myaspapp to the exemple)
and docker-compose.Tye.yml
```yaml
services:
  - name: myaspapp
    project: myaspapp.csproj
    env:
    - name: ASPNETCORE_ENVIRONMENT
      value: "foo"
```

This way it should with docker-compose use the image "myapps/myaspapp" and with tye use the project file myaspapp.csproj and define 'ASPNETCORE_ENVIRONMENT'. The naming would help to tye to understand wich one it should use. And i wont be weird to add in few years :
docker-compose.yml
- docker-compose.Tye.yml
   - docker-compose.local.Tye.yml
