### ISSUE TITLE
Support for replacement tokens

### ISSUE THREAD

**Issue by davidfowl** [dotnet/tye#223]
### What should we add or change to make your life better?
When dealing with systems that are configuration file based or command line argument based (launching a process), it should be possible to resolve values that are specified as environment variables. Take for example running nginx:

```yaml
name: apps-with-ingress
services:
- name: ingress
  image: nginx
  bindings:
    - port: 8080
  volumes:
    - source: nginx.conf
      target: /etc/nginx/conf.d/default.conf
- name: appA
  project: ApplicationA/ApplicationA.csproj
  bindings:
    - port: 5005
- name: appB
  project: ApplicationB/ApplicationB.csproj
  bindings:
    - port: 5006
```

The configuration file for nginx looks like this:

```
server {
    listen 80;

    location /A {
        proxy_pass http://host.docker.internal:5005/;
    }

    location /B {
        proxy_pass http://host.docker.internal:5006/;
    }
}
```

The above hardcodes the host and port of the upstream services. This is unfortunate and instead we want to write something that looks like this:

```
server {
    listen 80;

    location /A {
        proxy_pass http://{A_SERVICE_HOST}:{A_SERVICE_PORT}/;
    }

    location /B {
        proxy_pass http://{B_SERVICE_HOST}:{B_SERVICE_PORT}/;
    }
}
```
To make this work, the docker container has to run a command (envsubst) that substitutes the env variables in the files for their values. We could make this automatic.

### Why is this important to you?
It makes it possible to do use the tye service discovery and auto injection of context in more cases
