### ISSUE TITLE
per project tye.yaml & merge on tye deploy

### ISSUE THREAD

**Issue by spboyer** [dotnet/tye#239]
Pattern similar to helm charts where each service can have its own and apply on deployment.

**Comment by rynowak** [comment]
I've done a little bit of thinking about this.

## Summary

The main issue to solve is the impedence mismatch inherent between development and deployment in the case where you have one service per git repo (which is pretty common), so that you can have a CI/CD pipeline per service:

- You want **all** of the deployment details of each service to live in its repo so that services are individually and repeatedly deployable
- You need to be able to reason about other services (not in your repo) for development

---

Some other tools kinda dodge this problem, or don't face it because they aren't doing the same things we are.

- docker-compose doesn't have deployment
- skaffold has dev and deployment for multiple services, but doesn't really try to abstract over dependencies or k8s

[Garden](https://garden.io) is pretty similar to Tye in goals (it is also  much more mature). Garden has a per-repo/per-application configuration file (`garden.yaml`), and per-container/pre-project config files. *Note that I am using our terminology to describe them in order to draw parallels.*

Garden also has a fairly sophisticated system for working with multiple repositories: https://docs.garden.io/advanced/using-remote-sources#importing-remote-repositories

## Rationale (why this matters)

CI/CD systems that people use are either, *a:* really advanced and able to figure out what part of a source tree needs to build/deploy, or *b:* not really advanced at all 😆.

One of the core value propositions of microservices is to deploy separately, and today creating multiple repositories is a really straightforward way to achieve. Part of our community achieves success today by scripting the creation of new repos with all of the associated boilerplate and CI definitions when they want to add a service. This usually leads to the kind of development pain that Project Tye is trying to solve. 

Some set of developers is using single-repo strategies to achieve success today, and they have either invested a lot of hard work into CI/CD customization, or are just deploying everything on every build. That's fine too, but we need to set our bar at meeting the more complex set of requirements. 

## Goals

Some goals that hopeful we agree upon for what success means for a feature like this:

- Support multi-repo development and deployment scenarios as first-class
- Don't make support for single-repo worse
- Keep things simple (don't require submodules or worse for basic scenarios)
- Make the experience match between multi-repo and single-repo (same commands, properties, etc) 

## Future considerations

Right now we have **minimal** configuration for what we do in deployment. We're missing all kinds of knobs and dials that might apply. I'm going to call out some features that might impact deployment in the future that are cross-cutting (apply to the application instead of a single service).

- environments/profiles (where are you deploying to)
- other services and their bindings (service discovery wiring is deployment time)
- extensions (dapr, others)
- other application-wide k8s things like ingress (ingress rules are local, which controller is possibly not)

## Options

I'm going to assume that an application is made up of 3 services, with redis and postgres running locally as dependencies. I'm going to assume that each of these services has its own repo, with its own CI/CD pipeline. There is no "universe" repo where they all build together as submodules.

(what tye.yaml would look like for this in the single-repo case)

```yaml
name: cool-app
services:
- name: frontend
   project: ./frontend/frontend.csproj
- name: inventory
   project: ./inventory/inventory.csproj
- name: orders
   project: ./orders/orders.csproj
- name: redis
  container: redis
  bindings:
  - port: 6793
- name: postgres
  container: postgres
  bindings:
    - port: 5432 
```

I'm going to describe how some tweaks and pivots can enhance this scenario with callouts to what needs to change in the single-repo scenario where appropriate.

## Option 0 (do nothing)

*In the spirit of crawl-walk-run, here's where we are right now for multi-repo*.

You can put `tye.yaml` in each of your 5 repos, and construct convention-based relative paths:
- This breaks on your CI because those directories don't exist (other repos)
- If you workaround this then when you deploy it deploys all five services instead of the one you wanted

(tye.yaml in the frontend repo)

```yaml
name: cool-app
services:
- name: frontend
   project: ./frontend/frontend.csproj
- name: inventory
   project: ../inventoryrepo/inventory/inventory.csproj
- name: orders
   project: ../ordersrepo/orders/orders.csproj
- name: redis
  container: redis
  bindings:
  - port: 6793
- name: postgres
  container: postgres
  bindings:
    - port: 5432 
```

This is bad for a bunch of reasons:

- It doesn't actually work 😆 
- It duplicates all of the information, including details about paths in other repos

What's good about it is that it's actually preserved our ability to run locally unchanged 👍 

### Option 1: Slimmed down tye.yaml per repo

Another option would be to have a tye.yaml in each repo that only lists the things that concern that service.

(tye.yaml in the frontend repo)

```yaml
name: cool-app
services:
- name: frontend
   project: ./frontend/frontend.csproj
- name: inventory
  external: true
  bindings:
  - http
- name: orders
  external: true
  bindings:
  - http
```

In this example we've captured all of the details about the frontend app as well as the dependencies that it wants to consume. Listing the dependencies is necessary, because we need to know about them at manifest/deployment time.

What's bad about it:

- Still duplicates any global configuration that is needed for deployment (not shown in this example)
- Have to manually capture what all of the dependencies are 
- Doesn't answer *how* you aggregate all of these repos for local development

It seems pretty minimal so far though, and it's pretty close to something we could scaffold. 

One thing that I like is that all of the dependency-related information is semantic. The application developer cares that there is another service called `inventory`, and cares that they can talk to it over `http`. This information can be leveraged by a linting tool, or validated at dev-time.

If we take this approach (list the services you call into), then we have to make sure it behaves strictly in development, so you don't deploy to prod and then find out you did it wrong.

## Option 2: change the level of abstraction

We should remove some of the cross-repo knowledge that's spilt across repos by changing the level of abstraction. This would require a different vocabulary than what we have today, but it might be worth a look.

Here's what I mean. We'd drop the idea of service-discovery by default for **your other service** in production, and rely on DNS. This is less of a good idea if we're not talking about k8s.

We would still provide production features for secrets/connection strings.

(tye.yaml in the frontend repo)
```yaml
name: cool-app
services:
- name: frontend
   project: ./frontend/frontend.csproj
```

The bindings to `external` services go away because they are only meaningful in dev (where they are injected by default). 

---

(tye.yaml in the inventory repo - using an example with data sources instead of just other services)

```yaml
name: cool-app
services:
- name: inventory
   project: ./inventory/inventory.csproj
- name: redis
  external: true
- name: postgres
  external: true
```

Here we have bindings to redis and postgres because we want to be injected with those connection strings (this has to be known at manifest/deployment time).

---

What's bad about it:

- Still duplicates any global configuration that is needed for deployment (not shown in this example)
- Differences in how we behave between dev and production. 
- Doesn't answer *how* you aggregate all of these repos for local development

What's good about it:

- Less duplication of information about **your services**

## Global Configuration

We could try to mitigate the problem of duplicating global information in a few ways:

- Allow it to live in a separate file that can be synced across repos without conflicts.
- Allow it to be passed in at the commandline so that it doesn't have to be in source control, it can live in a CI pipeline.
- Allow partial copies

This of course assumes that we've got a problem to solve re: duplication of globals. Some of the features that we're talking about right now like `Ingress` make this relevant. We should thing about trying to design experiences that don't rely on global configuration that *trickles down* to affect deployment behavior of an individual service. This might just fundamentally be at odds with some of what we're trying to do.

*Note: It doesn't seem like garden attempts to mitigate this problem. Every repo you're working in has a garden.yaml (application) as well as one or many component files (service).*

## Experiences for aggregation

One of the questions left solved is "where do you keep the `tye.yaml` that aggregates my services for local dev?". 

This problem seems kinda vexxing at first, because it's a code organization problem - it's not really important us - but it's usually important to users that we provide good guidance.

Then, I got inspired by looking at what garden does (as well as some of our future goals). Put on your imagination hat and start thinking big....

Imagine with me that tye had the following:

- A way to configure a repo/feed (could be an OCI registry)
- A way to configure a local *GITPATH* (similar to *GOPATH*)
- A way to configure pointers to other git repositories in a tye.yaml (like garden)

This starts to become really cool once you have these primitives. Your team/company could build a catalog of `tye.yaml` files that are shared and maintained together. These could be accessible either via a git repo, or as OCI assets. 

Then you pick one you want to work on. You can select in a UI or command line which services you want to build from source, and which you want to get as containers. 

Then tye will clone all of the repositories, and either open it in VSCode multi-root workspace mode, or generate a `.sln` and open in VS, and you're good to go.

## Conclusion

I feel like we wouldn't be in a terrible place doing option 1, but the more I think about it option 2 really appeals to me. The spirit of minimalism hath caused my soul to take flight.

My main takeaway from this thought experiment is how much our goal of *thinking about the application as a whole* is in tension with correctness for many of the features we want to build. We can't assume that you have the whole application's code on hand, or even all of its manifests at any point. We can't assume that services are deployed in any particular order, or in phases. Etc.

**Comment by davidfowl** [comment]
Why can't we apply the same ideas that you would if you wanted to use another project as a dependency? Isn't this where packaging and dependencies come in?

Maybe the concept of an application is service specific and the `tye.yaml` is what I need to run this service locally and deploy it independently. Sure there's some duplication but I think it only needs to exist for 

- The inventory service is used by everything so it has no dependencies

```yaml
name: cool-app
services:
- name: inventory
   project: ./inventory/inventory.csproj
- name: redis
  container: redis
  bindings:
  - port: 6793
- name: postgres
  container: postgres
  bindings:
    - port: 5432 
```

- Orders relies on postgres.

```yaml
name: cool-app
services:
- name: orders
   project: ../ordersrepo/orders/orders.csproj
- name: postgres
   container: postgres
   bindings:
    - port: 5432 
```

- The frontend needs everything

```yaml
name: cool-app
services:
- name: frontend
  project: ./frontend/frontend.csproj
- name: inventory
  package: inventory/1.0.0
- name: orders
  package: orders/1.0.0
- name: redis
  container: redis
  bindings:
  - port: 6793
- name: postgres
  container: postgres
  bindings:
    - port: 5432 
```

This lets you avoid rebuilding services you don't own and may not have the tech to build (though docker "solves" this). It also lets you describe your view of the world with minimal duplicate information.

Thoughts?
