### ISSUE TITLE
tye package references

### ISSUE THREAD

**Issue by davidfowl** [dotnet/tye#29]
The idea behind this command is to enable sharing of tye manifests. `tye pack` would convert projects to container images and would put that in an archive (maybe a nuget package).  `tye.yml` would also be extended to reference these manifests as dependencies for consumption. The idea is that I can share a set of services so that another team can depend on them. 

Imagine the following:

Team B works on the backend API which relies on redis for caching.

```yml
# tye application configuration file
# read all about it at https://github.com/dotnet/tye
name: backend-services
services:
- name: backend
  project: backend\backend.csproj
- name: redis
  dockerImage: redis
  bindings:
    - port: 6379
```

They run the `tye pack` command and it produces a package that can be pushed to a feed to share the manifest. It also containerizes the backend project, pushes it to a registry (which maybe should be burned into the manifest)

```
tye pack
Building container image backend for backend\backend.csproj
Pushed docker image: 'davidfowl/backend:1.0.0'
Package 'backend\backend-services.1.0.0.nupkg'
```

Now team A (the front end team) can reference backend as a package in their tye manifest.

```yml
name: frontend
services:
- name: frontend
  project: frontend\frontend.csproj
- name: backend
  package: backend/1.0.0  # package reference
```

`tye run` will download this package from the feed (using feeds specified in `nuget.config`) and will grab the `tye.yml` file from that package and will run it as part of the services locally.

**Comment by davidfowl** [comment]
I think we need to front load this to see if it can "solve" some of the problems with multi repo development https://github.com/dotnet/tye/issues/239.

**Comment by davidfowl** [comment]
# Tye Packages

Consider the following application broken into 2 repositories:

**Frontend Team**
- MyApp.Frontend

**Backend Team**
- MyApp.Backend
- MyApp.Worker 
- RabbitMq

## Option 1

Package each application as nuget packages with the publish contents and push them to a nuget feed.

FrontEnd Team makes:

- **MyApp.Frontend.1.0.0.nupkg**

Backend Team makes:

- **MyApp.Backend.1.0.0.nupkg**
- **MyApp.Worker.1.0.0.nupkg**

Frontend team's `tye.yaml`

```yaml
name: multi-project
services:
- name: frontend
  project: frontend/frontend.csproj
  replicas: 2
  bindings:
  - port: 8000
- name: backend
  package: MyApp.Backend
  version: 1.0.0
  bindings:
  - port: 7000
- name: worker
  package: MyApp.Worker
  version: 1.0.0
- name: rabbit
  image: rabbitmq:3-management
  bindings:
    - port: 5672
```

In this model the backend's team breaks up their services into individual packages that are runnable that the frontend
team can consume. The frontend team still has to understand how the compose the backend teams' transitive dependencies 
and how to configure them in their `tye.yaml`.

## Option 2

Package the entire application as a nuget package. We would treat this like a single "service". This encapsulates 
multiple services as a single service.

FrontEnd Team makes:
- **MyApp.Frontend.1.0.0.nupkg**

Backend Team makes a package that contains the backend and worker projects as published assets with the `tye.yaml`
that describes how to run the service.

backend.1.0.0.nupkg

```
/backend/
/worker/
/tye.yaml
/backend.nuspec
```

The frontend team consumes the service in their `tye.yaml` like this:

```yaml
name: multi-project
services:
- name: frontend
  project: frontend/frontend.csproj
  replicas: 2
  bindings:
  - port: 8000
- name: backend
  package: backend
  version: 1.0.0
```

## Option 3

A mix of option 1 and 2 allows you to have 2 different packages. The top level meta-package with a `tye.yaml`
that also references other projects as packages (a meta package).

**backend.1.0.0.nupkg**

tye.yaml

```yaml
name: multi-project
services:
- name: frontend
  project: frontend/frontend.csproj
  replicas: 2
  bindings:
  - port: 8000
- name: backend
  package: backend
  version: 1.0.0
```

Open questions:
- What does the `name` section of the manifest mean? Is that the overall application name or the name of this slice of the multi-service application?
- Do we want to use nuget in the long run? I think we should start with it because it's easier.
- Can you override settings of services that come via transitive package dependencies? (Set extra env vars, change ports). This is akin to hoisting dependencies in nuget.
- Can you tye deploy these packages? Are these packages useful for anything else?
