### ISSUE TITLE
Specify URL from service to open by default

### ISSUE THREAD

**Issue by scottsauber** [dotnet/tye#373]
### What should we add or change to make your life better?
Something I thought of when I got off the call.  Maybe an option in the `tye.yaml` to open a particular URL on a particular service by default when you do `tye run`.  So if I have a UI or API service that fronts the other services, it just auto opens in my browser if I have that option specified.  So like below it would open http://localhost:whateverport/dashboard in the yaml below
```yaml
services:
- name: frontend
  startUrl: /dashboard
   # other settings
- name: backend
```

I realize this could potentially be awkward if someone is just hosting an executable though.

### Why is this important to you?
Saves a step of trying to find the URL from the terminal or from the dashboard.
