### ISSUE TITLE
Support replacement tokens in environment variables

### ISSUE THREAD

**Issue by davidfowl** [dotnet/tye#377]
This is a sample of an application that has an opiniated view of what env variables to use for ports. It wants to reference the tye's generated ports in the env variables (see below for an example).

```yaml
name: cornflake
 
services:
  - name: cornflake
    replicas: 3
    project: cornflake/cornflake.csproj
    bindings:
    - name: gateway
      port: 11111
    - name: silo
      port: 30000
    - name: web
      port: 5000
    env:
     - name: ENV_SILO_PORT
       value: ${service:cornflake:silo:port}
     - name: ENV_GATEWAY_PORT
       value: ${service:cornflake:gateway:port}
```

**Comment by TimHess** [comment]
Steeltoe supports [resolving property placeholders in configuration values](https://steeltoe.io/docs/2/configuration/placeholder-provider)

**Comment by davidfowl** [comment]
@TimHess that's pretty cool! We have a request to support something similar in configuration.

**Comment by rynowak** [comment]
We want to do a different proposal to this. We're going to make it possible to add an alias to a binding, so that the value it provides can be used in a configurable environment variable.

**Comment by Kralizek** [comment]
Totally a +1 to this issue!

This is the case I am facing:

```yaml
  - name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    env:
      - name: discovery.type
        value: single-node
    tags:
      - resources
      - search
    bindings:
      - containerPort: 9200
        protocol: http
        connectionString: "${host}:${port}"
  - name: search-resource-access
    project: ./ResourceAccess/SearchResourceAccess/src/SearchResourceAccess.Host/SearchResourceAccess.Host.csproj
    tags:
      - ras
      - search
    env:
      - name: SearchUri
        value: "${env:CONNECTIONSTRINGS__ELASTICSEARCH}"
```

Like specified in the opening post, this application expects the connection string to elasticsearch in the configuration key "SearchUri". Being an older project, I don't have the possibility to use `Configure<TOptions>` and refactoring this application to accomodate this need is beyond the scope of my research.

```json
    "replicas": {
      "search-resource-access_80a73db4-1": {
        "dockerCommand": null,
        "containerId": null,
        "dockerNetwork": null,
        "dockerNetworkAlias": null,
        "name": "search-resource-access_80a73db4-1",
        "ports": null,
        "exitCode": null,
        "pid": 3392,
        "environment": {
          "DOTNET_ENVIRONMENT": "Development",
          "ASPNETCORE_ENVIRONMENT": "Development",
          "DOTNET_LOGGING__CONSOLE__DISABLECOLORS": "true",
          "ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS": "true",
          "DOTNET_ROOT": "C:\\Program Files\\dotnet",
          "DOTNET_MULTILEVEL_LOOKUP": "0",
          "PATH": "<omitted>",
          "SearchUri": "${env:CONNECTIONSTRINGS__ELASTICSEARCH}",
          "CONNECTIONSTRINGS__ELASTICSEARCH": "localhost:10551",
          "APP_INSTANCE": "search-resource-access_80a73db4-1"
        },
        "state": "ready"
      }
```

**Comment by cjaliaga** [comment]
The case @Kralizek mentioned it's interesting and I think would be really useful. Imagine for example we are using the same service for starting a SQL Server but we'd like to define in another service 2 connection strings, one per database:

```yml
services:
  - name: sql
    image: mcr.microsoft.com/mssql/server:2019-latest
    bindings:
      - port: 1433
        connectionString: Server=tcp:${host},${port};User ID=SA;Password=Password123;
  - name: api
    project: API/API.csproj
    env:
      - name: CONNECTIONSTRINGS__APPDB
        value: "${env:CONNECTIONSTRINGS__SQL};Database=App"
      - name: CONNECTIONSTRINGS__UNICORNSDB
        value: "${env:CONNECTIONSTRINGS__SQL};Database=Unicorns"
```

**Comment by robertsundstrom** [comment]
@cjaliaga I'm looking for something like thos. I want to have one instance of MSSQL service with multiple databases/connection strings.

**Comment by alexdresko** [comment]
In my case, I want to do something like:

```
services:
- name: api
  project: src/microservices/api/api.csproj
- name: web
  executable: cmd
  args: '/c npm run start --prefix src/web -- --web-port ${this.port} --api-port ${api.port}`'
```

The goal is to let `web` start on any available port, but also tell `web` where `api` is.  `web` is a pure HTML/CSS/JS application, and we rely on the framework's (aurelia, in this case) dev server during development because it provides the best experience.

**Comment by alexdresko** [comment]
I don't know what's involved to satisfy my requirements, but it seems like a relatively easy problem to solve. Would I be wasting my time if I forked it and took a stab?

**Comment by robertsundstrom** [comment]
I ended up overloading GetConnectionString() with an extension method that appends the $"Database={database}" to the original output.

**Comment by davidfowl** [comment]
We would accept a PR for this if we can flesh out the design in this issue.

**Comment by alexdresko** [comment]
I'm considering compiling a list of requirements based on what is in this and a few other issues. For example, I wonder if the token/variable system could be extended to support multiple tye "instances", as in [this issue](https://github.com/dotnet/tye/compare/main...JPTaljaard:jptaljaard/multiple-instances). <-- a neat feature, BTW.

**Comment by tungphuong** [comment]
@TimHess and @davidfowl, Steeltoe is working fine with me. These are some additional steps
- In Tye.yaml
```
   name: postgres
    image: postgres:11-alpine
    env_file:
      - .env
    bindings:
      - name: port
        port: 5432
        connectionString: Server=${host};Port=${port};User Id=${env:USER};Password=${env:PASSWORD};
```
- Program
```
Host.CreateDefaultBuilder(args)
      .ConfigureAppConfiguration((context, config) =>
      {
          config.AddJsonFile("appsettings.json", optional: true);       
          ....
          config.AddPlaceholderResolver();
      })
....
```
- appsettings.json
```
"ConnectionStrings": {
    "default": "${connectionstrings:postgres?no_connection};Database=<your database>;"
  },
```
However, if Tye can support this feature, it will be better.

**Comment by Kralizek** [comment]
Bump :)

**Comment by JarradPosey** [comment]
I agree this would be a useful feature, when dealing with non-dotnet services. My use case is to add a `pgweb` dashboard to `postgres` without the need to add a new connection each time I restart tye. I would need to configure the `DATABASE_URL` variable with the value from the connection string `CONNECTIONSTRINGS__POSTGRES__PGWEB`. 

``` yaml
- name: postgres
  image: docker.io/library/postgres
  env:
  - name: POSTGRES_USERNAME
    value: postgres
  env_file:  
  - .secrets/.env
  volumes:
  - source: .postgres
    target: /var/lib/postgresql/data
  bindings:
  - name: pgweb
    protocol: tcp
    containerPort: 5432
    connectionString: postgres://${env:POSTGRES_USERNAME}:${env:POSTGRES_PASSWORD}@${host}:${port}/postgres?sslmode=disable
  - name: backend
    protocol: tcp
    containerPort: 5432
    connectionString: Server=${host};Port=${port};Username=${env:POSTGRES_USERNAME};Password=${env:POSTGRES_PASSWORD};

- name: pgweb
  image: docker.io/sosedoff/pgweb
  env:
    - name: SESSIONS
      value: '1'
    - name: DATABASE_URL
      value: ${env:CONNECTIONSTRINGS__POSTGRES__PGWEB}
  bindings:
    - protocol: http
      containerPort: 8081
```
