### ISSUE TITLE
Only inject ASPNETCORE_URLS for ports defined as http or https

### ISSUE THREAD

**Issue by davidfowl** [dotnet/tye#379]
### Describe the bug
Today we inject all ports as ASPNETCORE_URLS port but if something else is binding to other ports in the same process it will result in a port conflict:

### To Reproduce

```yaml
name: cornflake
 
services:
  - name: cornflake
    replicas: 3
    project: cornflake/cornflake.csproj
    bindings:
    - name: gateway
      port: 11111
    - name: silo
      port: 30000
    - name: web
      port: 5000
      protocol: http
```

In the above application, the Kestrel wants to bind to port 5000, but something else will bind to 11111 and 30000.
