### ISSUE TITLE
Need a clear guidance on how to run --logs with seq and --dtrace with Zipkin

### ISSUE THREAD

**Issue by thangchung** [dotnet/tye#399]
Currently, I spent a lot of time to search around in this repository, but could not find out the way to run `--logs` with `seq`, and the same things for `--dtrace` with `zipkin`

I found the docs at https://github.com/dotnet/tye/blob/3f994be2fd4b9acaebb69a896141e154ffe9ae36/docs/reference/commandline/tye-run.md#options, and follow the guidance there

I could make it work with `tye run --logs console`, but couldn't with `seq`, and don't know how to setup it. If it is possible, could you please give clear guidance or an example of the `samples` section for it?

And the same thing with --dtrace on Zipkin, I read the source code, and try with `tye run --logs seq --dtrace zipkin=http://localhost:9411/api/v2/spans`

My type.yaml:

```yaml
name: practical-dapr
extensions:
- name: dapr
  log-level: debug
  config: appconfig
registry: vndg
services:
- name: sqlserver
  image: mcr.microsoft.com/mssql/server:2017-latest
  env:
    - name: SA_PASSWORD
      value: "P@ssw0rd"
    - name: ACCEPT_EULA
      value: "Y"
  bindings:
    - port: 1433
- name: redis
  image: redis
  bindings:
    - port: 6379
- name: zipkin
  image: openzipkin/zipkin
  bindings:
    - port: 9411
      containerPort: 9411
      protocol: http
- name: seq
  image: datalust/seq
  env:
    - name: "ACCEPT_EULA"
      value: "Y"
  bindings:
    - port: 5340
      containerPort: 5340
      protocol: http
- name: graph-api
  project: src/GraphApi/CoolStore.GraphApi/CoolStore.GraphApi.csproj
- name: identity-api
  project: src/Identity/CoolStore.IdentityServer/CoolStore.IdentityServer.csproj
- name: product-catalog-api
  project: src/ProductCatalog/CoolStore.ProductCatalogApi/CoolStore.ProductCatalogApi.csproj
- name: inventory-api
  project: src/Inventory/CoolStore.InventoryApi/CoolStore.InventoryApi.csproj
```

tye version: `0.2.0-alpha.20217.2+f41b9421834c16d6d3520c26b26fedecefa2b638`
OS: Windows 10

**Comment by thangchung** [comment]
Nevermind this discussion. I can handle it now. What I did as below for who wants to run `seq` and `zipkin` on `tye` tool

```yaml
name: practical-dapr
extensions:
- name: dapr
  log-level: debug
  config: appconfig
registry: vndg
services:
- name: sqlserver
  image: mcr.microsoft.com/mssql/server:2017-latest
  env:
    - name: SA_PASSWORD
      value: "P@ssw0rd"
    - name: ACCEPT_EULA
      value: "Y"
  bindings:
    - port: 1433
- name: redis
  image: redis
  bindings:
    - port: 6379
- name: zipkin
  image: openzipkin/zipkin
  bindings:
    - port: 9411
      containerPort: 9411
      protocol: http
- name: seq
  image: datalust/seq
  env:
    - name: "ACCEPT_EULA"
      value: "Y"
  bindings:
    - name: ui
      port: 5340
      protocol: http
      containerPort: 80
    - name: internal
      port: 5341
- name: graph-api
  project: src/GraphApi/CoolStore.GraphApi/CoolStore.GraphApi.csproj
- name: identity-api
  project: src/Identity/CoolStore.IdentityServer/CoolStore.IdentityServer.csproj
- name: product-catalog-api
  project: src/ProductCatalog/CoolStore.ProductCatalogApi/CoolStore.ProductCatalogApi.csproj
- name: inventory-api
  project: src/Inventory/CoolStore.InventoryApi/CoolStore.InventoryApi.csproj
```

And `tye` CLI:

```bash
$ tye run --dtrace zipkin=http://localhost:9411 --logs seq=http://localhost:5340
```

Then, you can access to Zipkin at http://localhost:9411

![image](https://user-images.githubusercontent.com/422341/80170529-5ca3e680-8612-11ea-8fd6-1c11987b6067.png)

And Seq at http://localhost:5340/

![image](https://user-images.githubusercontent.com/422341/80170564-6fb6b680-8612-11ea-9f30-5154a6cceb4c.png)

I gonna close this discussion now.
