### ISSUE TITLE
Environment variables / templating not working 

### ISSUE THREAD

**Issue by spboyer** [dotnet/tye#421]
Docs: https://github.com/dotnet/tye/blob/master/docs/reference/service_discovery.md

Given the following definition in tye.yaml

```
- name: mongo
  image: mongo
  env:
  - name: MONGO_INITDB_ROOT_USERNAME
    value: root
  - name: MONGO_INITDB_ROOT_PASSWORD
    value: example
  bindings:
  - port: 27017
    connectionString: "{$env:MONGO_INITDB_ROOT_USERNAME}:{$env:MONGO_INITDB_ROOT_PASSWORD}@${host}:${port}"  
    protocol: mongodb
```

The expected output should be : `mongodb://root:example@mongo:27017`

value returned in the container shows: 
`{$env:MONGO_INITDB_ROOT_USERNAME}:{$env:MONGO_INITDB_ROOT_PASSWORD}@mongo:27017`
