### ISSUE TITLE
Connectionstring_* ENV exists in all containers

### ISSUE THREAD

**Issue by spboyer** [dotnet/tye#422]
tye.yaml
```
name: todos
services:

- name: api
  project: api/api.csproj

- name: mongo
  image: mongo
  env:
  - name: MONGO_INITDB_ROOT_USERNAME
    value: root
  - name: MONGO_INITDB_ROOT_PASSWORD
    value: example
  bindings:
  - port: 27017
    connectionString: "{$env:MONGO_INITDB_ROOT_USERNAME}:{$env:MONGO_INITDB_ROOT_PASSWORD}@${host}:${port}"  
    protocol: mongodb

- name: mongo-express
  image: mongo-express
  env:
  - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
    value: root
  - name: ME_CONFIG_MONGODB_ADMINPASSWORD
    value: example
  bindings:
  - port: 8081
    protocol: http
```
**CONNECTIONSTRINGS__MONGO** is created as an environment variable and exists in all containers; mongo_*, api-proxy_*, mongo-express_*

There is not currently a way to define what container to inject the ConnectionString into for AppSettings. - feature request?

**Comment by jkotalik** [comment]
We are doing some work currently to make it so nested configurations do not inject environment variables in for non-dependent projects. This work isn't documented yet but will be soon. However, the hierarchy for dependencies is based on merging tye.yaml files, and couldn't be accomplished with a single tye.yaml file.

For example, you could have a repo structure like:

```yaml
name: test
services:
- name: a
  include: reference to another tye.yaml
- name: b
  project: b/b.csproj

...

# a's tye.yaml
name: test
services:
- name: a
  project: a/a.csproj
- name: mongo
  image: mongo
  env:
  - name: MONGO_INITDB_ROOT_USERNAME
    value: root
  - name: MONGO_INITDB_ROOT_PASSWORD
    value: example
  bindings:
  - port: 27017
    connectionString: "{$env:MONGO_INITDB_ROOT_USERNAME}:{$env:MONGO_INITDB_ROOT_PASSWORD}@${host}:${port}"  
    protocol: mongodb

```

With this setup, service b wouldn't get the CONNECTIONSTRINGS_MONGO injected into the process, only a.

Ultimately though, do you feel like injecting extra environment variables into process that don't need it is just a tad ugly?

**Comment by spboyer** [comment]
> Ultimately though, do you feel like injecting extra environment variables into process that don't need it is just a tad ugly?

It is ugly and potentially "appears" as if we are crossing containment boundaries when putting everything everywhere. It's convenient, but looks messy?

**Comment by rynowak** [comment]
I think if we gave you a way to control this, it would *look like* the ability to specify which services are dependencies of which other services.

That could be done implicitly with multiple files (Justin checked that in 👍) or explicitly in a single file.

```yaml
name: todos
services:

- name: api
  project: api/api.csproj
  dependencies:
  - mongo

- name: mongo
  image: mongo
  env:
  - name: MONGO_INITDB_ROOT_USERNAME
    value: root
  - name: MONGO_INITDB_ROOT_PASSWORD
    value: example
  dependencies:
  bindings:
  - port: 27017
    connectionString: "${env:MONGO_INITDB_ROOT_USERNAME}:${env:MONGO_INITDB_ROOT_PASSWORD}@${host}:${port}"  
    protocol: mongodb

- name: mongo-express
  image: mongo-express
  env:
  - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
    value: root
  - name: ME_CONFIG_MONGODB_ADMINPASSWORD
    value: example
  dependencies:
  - mongo
  bindings:
  - port: 8081
    protocol: http
```
