### ISSUE TITLE
Cannot host external http service via container

### ISSUE THREAD

**Issue by spboyer** [dotnet/tye#423]
### Describe the bug
mongo-express is a container that is a UI for interacting with mongodb. Internal port is 8081, should load via http://localhost:8081. Cannot hit endpoint.

```
- name: mongo-express
  image: mongo-express
  env:
  - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
    value: root
  - name: ME_CONFIG_MONGODB_ADMINPASSWORD
    value: example
  bindings:
  - port: 8081
    protocol: http
```

**Comment by davidfowl** [comment]
Our logic tries to make the container based http port by default but maybe that's too aggressive. You can do 2 things to work around this for now:
- Change port to containerPort - `containerPort: 8081` - This will generate a random non-conflicting public port fix the containerPort to 8081.
- Set both the port and containerPort to control both the exposed port and containerPort.

**Comment by spboyer** [comment]
Setting both `port` and `containerPort` does not appear to be a solution in this scenario. The dashboard shows.

http://localhost:8081 (does not resolve) http://localhost:58257 (good!)

Used only the `containerPort` and http://localhost:58257 is presented and works.

```
- name: mongo-express
  image: mongo-express
  env:
  - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
    value: root
  - name: ME_CONFIG_MONGODB_ADMINPASSWORD
    value: example
  bindings:
  - containerPort: 8081
    protocol: http
```

**Comment by spboyer** [comment]
here are the relevant logs:

```

Tell us what you think!
About
Logs for mongo-express
[mongo-express_742c31de-6]: docker run -d -v C:\Users\shboyer\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro -e "DOTNET_ENVIRONMENT=Development" -e "ASPNETCORE_ENVIRONMENT=Development" -e "DOTNET_LOGGING__CONSOLE__DISABLECOLORS=true" -e "ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true" -e "ASPNETCORE_URLS=http://*:8081;http://*:8081" -e "PORT=8081;8081" -e "PROXY_PORT=8081:50357;8081:8081" -e "ME_CONFIG_MONGODB_ADMINUSERNAME=root" -e "ME_CONFIG_MONGODB_ADMINPASSWORD=example" -e "SERVICE__API__PROTOCOL=http" -e "API_SERVICE_PROTOCOL=http" -e "SERVICE__API__PORT=80" -e "API_SERVICE_PORT=80" -e "SERVICE__API__HOST=api" -e "API_SERVICE_HOST=api" -e "SERVICE__API__HTTPS__PROTOCOL=https" -e "API_HTTPS_SERVICE_PROTOCOL=https" -e "SERVICE__API__HTTPS__PORT=443" -e "API_HTTPS_SERVICE_PORT=443" -e "SERVICE__API__HTTPS__HOST=api" -e "API_HTTPS_SERVICE_HOST=api" -e "CONNECTIONSTRINGS__MONGO=root:example@mongo:27017" -e "SERVICE__MONGO-EXPRESS__CONTAINERPORT__PROTOCOL=http" -e "MONGO-EXPRESS_CONTAINERPORT_SERVICE_PROTOCOL=http" -e "SERVICE__MONGO-EXPRESS__CONTAINERPORT__PORT=8081" -e "MONGO-EXPRESS_CONTAINERPORT_SERVICE_PORT=8081" -e "SERVICE__MONGO-EXPRESS__CONTAINERPORT__HOST=mongo-express" -e "MONGO-EXPRESS_CONTAINERPORT_SERVICE_HOST=mongo-express" -e "SERVICE__MONGO-EXPRESS__PORT__PROTOCOL=http" -e "MONGO-EXPRESS_PORT_SERVICE_PROTOCOL=http" -e "SERVICE__MONGO-EXPRESS__PORT__PORT=8081" -e "MONGO-EXPRESS_PORT_SERVICE_PORT=8081" -e "SERVICE__MONGO-EXPRESS__PORT__HOST=mongo-express" -e "MONGO-EXPRESS_PORT_SERVICE_HOST=mongo-express" -e "APP_INSTANCE=mongo-express_742c31de-6" -e "CONTAINER_HOST=host.docker.internal" -p 50357:8081 -p 8081:8081 --name mongo-express_742c31de-6 --restart=unless-stopped mongo-express
[mongo-express_742c31de-6]: 31023363b66377b1b795d4b97d23671ff788d10749bd940d2ba50b65a5c76b6e
[mongo-express_742c31de-6]: docker network connect tye_network_4bd89e29-6 mongo-express_742c31de-6 --alias mongo-express
```

**Comment by davidfowl** [comment]
Both looks like this:

```yaml
- name: mongo-express
  image: mongo-express
  env:
  - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
    value: root
  - name: ME_CONFIG_MONGODB_ADMINPASSWORD
    value: example
  bindings:
  - port: 8081
    containerPort: 8081
    protocol: http
```
