### ISSUE TITLE
No Tye equivalent for the command property in a docker file

### ISSUE THREAD

**Issue by amarie401** [dotnet/tye#446]
### Describe the bug
Tye does not currently support the command property.

```yaml
services:
  config:
    image: "steeltoeoss/configserver:1.3.2"
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
      - type: bind
        source: ./src/config
        target: /config
    ports:
      - "8888:8888"
```
### To Reproduce
I am looking for the equivalent of command in a docker file.
