### ISSUE TITLE
Dapr: Failed to init input binding with kafka and zookeeper

### ISSUE THREAD

**Issue by thangchung** [dotnet/tye#464]
I have tried to use `bindings.kafka` with `tye` following with the configuration file at 
https://github.com/dapr/samples/tree/master/5.bindings

I created `kafka_bindings.yaml` with the same content in the repo above

```yaml
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sample-topic
spec:
  type: bindings.kafka
  metadata:
  # Kafka broker connection setting
  - name: brokers
    value: localhost:9092
  # consumer configuration: topic and consumer group
  - name: topics
    value: sample
  - name: consumerGroup
    value: group1
  # publisher configuration: topic
  - name: publishTopic
    value: sample
  - name: authRequired
    value: "false"
```

And on `tye.yaml`, I added

```yaml
- name: zookeeper
  image: wurstmeister/zookeeper:latest
  bindings:
    - port: 2181
      containerPort: 2181
- name: kafka
  image: wurstmeister/kafka:latest
  bindings:
    - port: 9092
      containerPort: 9092
  env:
    - name: KAFKA_ADVERTISED_HOST_NAME
      value: 127.0.0.1
    - name: KAFKA_CREATE_TOPICS
      value: sample:1:1
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper:2181
```

In the application, I have the publisher using `dapr-dotnet`

```csharp
await _daprClient.InvokeBindingAsync("sample-topic", notification, null, cancellationToken);
```

And the `subscriber` as following

```csharp
[HttpPost("sample-topic")]
public async Task SubcribeSampleTopic(
    AddStoreProductPriceCommand command)
{
    // do something
    // ...
}
``

But when I run the application, I can start and run normally, but nothing happens when I `InvokeBinding`. I examined the logs file for the Dapr proxy and found out the error in there

```
[inventory-api-dapr_36a321be-a]: time="2020-05-09T20:27:45.1222329+07:00" level=info msg="found component sample-topic (bindings.kafka)" app_id=inventory-api instance=LAPTOP-7QC3O5QO scope=dapr.runtime type=log ver=0.7.0
....
[inventory-api-dapr_36a321be-a]: time="2020-05-09T20:27:46.9864866+07:00" level=error msg="failed to init output binding sample-topic (bindings.kafka): kafka: client has run out of available brokers to talk to (Is your cluster reachable?)" app_id=inventory-api instance=LAPTOP-7QC3O5QO scope=dapr.runtime type=log ver=0.7.0
[inventory-api-dapr_36a321be-a]: time="2020-05-09T20:27:47.7493515+07:00" level=error msg="failed to init input binding sample-topic (bindings.kafka): kafka: client has run out of available brokers to talk to (Is your cluster reachable?)" app_id=inventory-api instance=LAPTOP-7QC3O5QO scope=dapr.runtime type=log ver=0.7.0
```

My question is:
- I have searched around in this repo, but don't have anywhere that mentioned how to use Dapr binding using Kafka so how can I do it?
- Could we have to document somewhere about this one? Because I think it is quite popular in the microservice with Dapr.
- What I did wrong to make this error happened by using `kafka` and `zookeeper` with `tye`?

Tye: 0.2.0-alpha.20224.3+943b60d39155cdd44bee76daaf47dbc54d55f9e7
Dapr: 0.0.7
Windows 10 OS

**Comment by jkotalik** [comment]
> I have searched around in this repo, but don't have anywhere that mentioned how to use Dapr binding using Kafka so how can I do it?
> Could we have to document somewhere about this one? Because I think it is quite popular in the microservice with Dapr.

Yeah, we haven't gotten the chance to have a sample with Dapr + Kafka. We would gladly accept a sample or recipe if you manage to get that working.

> What I did wrong to make this error happened by using kafka and zookeeper with tye?

I'm not sure based on that error. Could you post this sample on git somewhere so I can clone and try locally?

**Comment by thangchung** [comment]
I have tried it at https://github.com/thangchung/practical-dapr/commit/53d091fdeabb65b11b978c34e878ce20c71b86ba

If you have time, please have a look at it.

In the meantime, I will continue to try with it, if that works, I will make a sample and PR

**Comment by MarcinKruszynski** [comment]
I have managed to use Kafka binding between two ASP.NET Core microservices:

Service with output binding:
`var notification = new NotificationData { BookingId = confirmation.BookingId };
 await dapr.InvokeBindingAsync("notifications-topic", "create", notification, null, default(CancellationToken)); `

Service with input binding:

       public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseCloudEvents();                        

            app.UseEndpoints(endpoints =>
            {               
                endpoints.MapPost("notifications-topic", ProcessNotification);               
            });

            async Task ProcessNotification(HttpContext context)
            {  
                var message = await JsonSerializer.DeserializeAsync<NotificationData>(context.Request.Body, options);

                Console.WriteLine("Hello from Kafka: Booking {0} confirmed.", message.BookingId);                                            
            }
        }

I have used endpoint without controller and UseCloudEvents().  

It works with Tye in Kubernetes (I have deployed Kafka & Zookeeper and Dapr Kafka binding component manually like in 
[https://github.com/dapr/samples/tree/master/5.bindings](url)).

It also works locally, but without adding Kafka and Zookeeper to tye.yaml file (I have used docker-compose file for Kafka and Zookeeper like in [https://github.com/dapr/samples/tree/master/5.bindings](url)), for the rest of my distributed sample app:  tye run).

I also have used Tye Dapr Extension for Dapr 0.8.0 workaround for locally running services (copying components/*.yaml to %UserProfile%.dapr\components [https://github.com/dotnet/tye/issues/555](url)).

So it seems there is a problem with Tye and Kafka & Zookeeper in tye.yaml when we use 'tye run'.

**Comment by cwuethrich** [comment]
I used Kafka with Tye in an other sample application.

```
- name: zookeeper
  image: confluentinc/cp-zookeeper:latest
  bindings:
    - port: 2181
      containerPort: 2181
  env:
    - name: ZOOKEEPER_CLIENT_PORT
      value: 2181
- name: kafka
  image: confluentinc/cp-kafka:latest
  bindings:
    - port: 9092
      containerPort: 9092
  env:
    - name: KAFKA_BROKER_ID
      value: 1
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper:2181
    - name: KAFKA_ADVERTISED_LISTENERS
      value: PLAINTEXT://localhost:9092
    - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      value: 1
    - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
      value: true
```
