### ISSUE TITLE
Setting DockerFileContext doesn't seem to work

### ISSUE THREAD

**Issue by amarie401** [dotnet/tye#471]
### Describe the bug
When manually specifying the DockerFileContext, it gives you the error message from Docker but not the command where it failed.

This doesn't work
```
- name: todo-client
  dockerFile: "./client/Dockerfile"
  dockerFileContext: ./client
  bindings:
    - containerPort: 80
      protocol: http
```

This works

```
- name: todo-client
  dockerFile: "./client/Dockerfile"
  bindings:
    - containerPort: 80
      protocol: http
```
