### ISSUE TITLE
Can I use angular with .net core with tye

### ISSUE THREAD

**Issue by rahulsahay19** [dotnet/tye#472]
Hi Team,

I have created a sample microservice kind of project as shown below

![image](https://user-images.githubusercontent.com/3886381/81787313-7acc7a80-951e-11ea-9ac1-66c67af74452.png)

Here, I have exclusively containerized angular project with the following code

```yaml
FROM node:alpine as node
ARG NPM_TOKEN

WORKDIR /src
COPY . .

RUN npm install && npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=node /src/dist /usr/share/nginx/html/movies

``` 
Then, tye.yaml file I configured like 

```yaml
# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: project-tye
services:
- name: moviesapi
  project: MoviesAPI/MoviesAPI.csproj
- name: moviesapp
  image: moviesapp:dev
  bindings:
  - port: 4400
    containerPort: 4400
    protocol: http
```

Since, random port wasn't getting assigned automatically to angular project, hence I did binding like this. Having said that, when I run tye run then it launched dashboard like shown below

![image](https://user-images.githubusercontent.com/3886381/81787796-32618c80-951f-11ea-9a5e-bdf655e67659.png)

Here, I can navigate to the API like shown below

![image](https://user-images.githubusercontent.com/3886381/81787885-4efdc480-951f-11ea-8ef2-36e33b0bfecf.png)

But, when I navigate to http://localhost:4400/movies it says

![image](https://user-images.githubusercontent.com/3886381/81787986-705eb080-951f-11ea-8923-d84ec98f8557.png)

Just wanted to know whether this use case is supported with tye. I know if I have any .Net app serving app instead of angular, it will work. And if this is valid usecase, then is there any thing which I am missing here?

I have also put this in github for your reference https://github.com/rahulsahay19/project-tye

Thanks

**Comment by davidfowl** [comment]
What do the logs say for the movies project?

**Comment by rahulsahay19** [comment]
Hi,

Here is the required stuff. Logs for movies App 

![image](https://user-images.githubusercontent.com/3886381/81861707-4be9ef00-9586-11ea-9fe8-faa27d03fa0c.png)

and logs for movies API

![image](https://user-images.githubusercontent.com/3886381/81861760-64f2a000-9586-11ea-8fad-86fa3b152351.png)

docker ps

![image](https://user-images.githubusercontent.com/3886381/81861884-8ce20380-9586-11ea-8138-457f2634fa4b.png)

Thanks.

**Comment by davidfowl** [comment]
And nginx is running on what port?

**Comment by rahulsahay19** [comment]
Yes, forgot to attach nginx. Added that as well. For that, I also created one docker file like shown below

```yaml
FROM nginx:latest

COPY nginx.conf /etc/nginx/conf.d/default.conf
```

And kept nginx.conf like this

```
worker_processes 1;

events { worker_connections 1024; }

upstream movies-app {
        server moviesapp:4400;
    }

server {
    listen 8080;

    location /movies {
        proxy_pass http://movies-app/;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}
```
There after, I modified the tye file like

```yaml
# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: project-tye
services:
- name: nginx
  image: nginx:latest
  bindings:
    # - port: 8080
    #   containerPort: 8080
    - protocol: http
  volumes:
    - source: NGINX/nginx.conf
      target: /etc/nginx/conf.d/default.conf

- name: moviesapi
  project: MoviesAPI/MoviesAPI.csproj
  
- name: moviesapp
  image: moviesapp:dev
  bindings:
  - port: 4400
    containerPort: 4400
    protocol: http
```
Afterwards, dashboard comes like 

![image](https://user-images.githubusercontent.com/3886381/81867176-eef23700-958d-11ea-908d-932a4e4b5d95.png)

And nginx logs comes like

![image](https://user-images.githubusercontent.com/3886381/81867708-c4ed4480-958e-11ea-9243-c5239de83386.png)

Therefore, revised project structure looks like 

![image](https://user-images.githubusercontent.com/3886381/81867863-fcf48780-958e-11ea-9d7b-fa7095847151.png)

Now, Repo looks like 

![image](https://user-images.githubusercontent.com/3886381/81868982-e0f1e580-9590-11ea-9374-cb421b723c26.png)


Also updated the same in repo at https://github.com/rahulsahay19/project-tye. Not sure, if there is anything wrong I am doing with nginx.conf. 

Thanks.

**Comment by davidfowl** [comment]
I spent some time playing with this:
- You don't need the 3rd nginx service (you can remove it)
- The port you have configured for nginx is incorrect
- I couldn't get your moviesapp working, maybe the static files arent configured properly or I was hitting the wrong address

This should be the minimum:

```yaml
name: project-tye
services:
- name: moviesapi
  project: MoviesAPI/MoviesAPI.csproj
  
- name: moviesapp
  image: moviesapp:dev
  bindings:
  - protocol: http
```
