### ISSUE TITLE
Service discovery for databases

### ISSUE THREAD

**Issue by tmds** [dotnet/tye#476]
Service discovery for databases doesn't include the type of database (e.g. mssql, PostgreSQL, ...)

**Proposal**

The service discovery for databases can also use the `SERVICE__` prefix.

This means `CONNECTIONSTRING__USERS` becomes `SERVICE__USERS__CONNECTIONSTRING`.

The `__PROTOCOL` suffix can then be used to indicate the type of database: e.g.: `SERVICE__USERS__PROTOCOL=postgresql`.

An extension method can be added on `IConfiguration` to `GetServiceProtocol`.

cc @rynowak @jkotalik @davidfowl

**Comment by jkotalik** [comment]
What does your tye.yaml look like for this? I think adding that extension method makes sense, however I think we'll need to require people to specify the protocol rather than trying to infer it from the connection string, ex:

```yaml
- name: postgres
  image: postgres
  bindings:
    - port: 5555
      connectionString: <connectionstring>
      protocol: postgres
```
