### ISSUE TITLE
Env variables placeholder

### ISSUE THREAD

**Issue by mustakimali** [dotnet/tye#486]
I was assessing the suitability of `tye` in a project and I have few questions that I don't know if they are possible.

## 1. Can we use placeholders in environment
consider following scheme, I want to pass the port of `app2` into `app1` as an environment variable.

```yaml
name: tye-them-all
services:
- name: app1
  project: src/app1/app1.csproj
  env:
    - name: APP2_BASE_URL
      value: "http://localhost:{app2_port}/"
- name: app2
  project: src/app2/app2.csproj
  bindings:
    - autoAssignPort: true
```

## 2. Run initialisation scripts for projects and containers
We may need to run some initialisation scripts that run after a container/project is running.

```yaml
name: tye-them-all
services:
- name: app1
  project: src/app1/app1.csproj
  # script should have access to ${postgres_port} env variable
  init_script: scripts/init-db.sh

- name: postgres
  image: postgres
  bindings:
  - autoAssignPort: true
```

## 3. Define orders
The previous suggestion will work better if we can define the order or dependencies between services.
```yaml
name: tye-them-all
services:
- name: app1
  project: src/app1/app1.csproj
  # script should have access to ${postgres_port} env variable
  init_script: scripts/init-db.sh
  requires: ["postgres"]

- name: postgres
  image: postgres
  bindings:
  - autoAssignPort: true
```

Thank you for your help. :+1:
