### ISSUE TITLE
Adding tags to yaml services definitions to be used in CLI run filter

### ISSUE THREAD

**Issue by kkoziarski** [dotnet/tye#493]
### What should we add or change to make your life better?
Ability to tag services, 
``` yaml
name: myapplication
services:
- name: backend
  project: backend/backend.csproj
  tags:
  - tag1
  - tag2
- name: worker
  project: worker/worker.csproj
  tags:
  - tag3
```
and then use these tags in CLI to run only a subset of services:
``` powershell
tye run --tags=tag1,tag3
```
### Why is this important to you?
While I develop (on localhost) a system which has dozens of services, I usually don't need them all running on the same time and I would like to have the ability to run them by tags - grouped by modules or categories.

**Comment by davidfowl** [comment]
This is interesting, I have more questions:
- How many services do you have locally?
- Are these services in a mono repo?
- Are they deployed together?

**Comment by kkoziarski** [comment]
- I have ~30 services, half of them are workers/BackgroundServices and another half are APIs and this is evolving
- This is mono repo
- They are deployed together from AzureDevOps

At the moment I'm not going to use tye for deployment, only for local development. Now I have a single `.bat` script running all services by `dotnet run` and if I want to save my PC's resources I comment out some lines in that file which is far from perfect.

To be able to login, I need ~5 services running, and very often this is all I need, because I need to get JWT and use it for debugging in VS+Postman.

**Comment by davidfowl** [comment]
One more question, is there a single team working in this repo?

**Comment by kkoziarski** [comment]
Yes, single team + DevOps

**Comment by davidfowl** [comment]
Yep next milestone unless we get a generous contribution 😄

**Comment by jkotalik** [comment]
I think this a fairly good first issue 😄.

**Comment by kkoziarski** [comment]
I can try to do this, but it won't be fast and I hope it won't be too naive 😄

**Comment by kkoziarski** [comment]
@davidfowl @jkotalik should I add tags to `ingress` and/or `extensions` too?

``` yaml
ingress:
  - name: ingress
    bindings:
      - port: 8080
    tags:
      - tagA
      - tagB
```
