### ISSUE TITLE
Api gateway support

### ISSUE THREAD

**Issue by nripendra** [dotnet/tye#522]
This is some what related to ingress. Currently it doesn't seem possible to route same base URLs to different services. E.g. I want to route /api/controller1 to service A, while routing /api/controller2 to service B. 

Currently it is possible to have route like /A/api/controller1 etc, but it leaks the service implementation details to consumers. If someday I plan to move some api to new microservice without changing the contracts, all consumer will still have to make changes, although contracts hasn't changed. 

I tried integrating ocelot but since service's host and port are dynamic, I wasn't able to. It would be helpful if I could atleast use service names for host, and expose inter service ports similar to what docker-compose does.

**Comment by jkotalik** [comment]
To make sure I understand, why couldn't you do something like:
```yaml
name: apps-with-ingress
ingress:
  - name: ingress
    bindings:
      - port: 8080
    rules:
      - path: /api/controller1
        service: app-a
      - path: /api/controller2
        service: app-b
```

**Comment by nripendra** [comment]
I tried this but all my requests were being redirected to first service. At least that's what the behavior looked like to me. May be I got it wrong, 
I will give it one more try, when I have some time. If it works then, I will close the issue.

**Comment by jkotalik** [comment]
That seems like a bug on our side if that doesn't work. If you can provide a sample for us, that would speed up the investigation.

**Comment by nripendra** [comment]
@jkotalik I had done some investigation here. Let's say we have following ingress config:
```
name: apps-with-ingress
ingress:
  - name: ingress
    bindings:
      - port: 8080
    rules:
      - path: /api/controller1
        service: app-a
      - path: /api/controller2
        service: app-b
```
Now, I have to request with `/api/controller1/api/controller1` to reach `/api/controller1` route in app-a. With this behaviour, as I mentioned in my original post, I will have to configure ingress to point something like `/A` to app-a, so that `/A/api/controller1` reaches app-a's `api/controller1` route. 

Current behaviour may be ideal for some scenarios, but I'm looking for the path `/api/controller1` to be part of the forwarded request, is it configurable?
