### ISSUE TITLE
Schema validation in VS Code fails with valid tye.yaml

### ISSUE THREAD

**Issue by rynowak** [dotnet/tye#533]
Following the instructions [here](https://github.com/dotnet/tye/tree/master/src/schema) results in errors like the following for every service name.

```txt
Matches multiple schemas when only one must validate.
```

Example tye.yaml that reproduces this:

```yaml
# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: voting
services:
- name: vote
  project: vote/vote.csproj
- name: worker
  project: worker/worker.csproj
- name: results
  project: results/results.csproj
- name: redis
  image: redis
  bindings:
  - port: 6379
    connectionString: ${host}:${port}
- name: postgres
  image:  postgres
  env:
  - name: POSTGRES_PASSWORD
    value: "pass@word1"
  bindings:
  - port: 5432
    connectionString: Server=${host};Port=${port};User Id=postgres;Password=${env:POSTGRES_PASSWORD};
```
