### ISSUE TITLE
Error when deploying with https bindings

### ISSUE THREAD

**Issue by JamesNK** [dotnet/tye#562]
I get an error when deploying with tye when tye.yaml is configured with https bindings.

```
name: microservice
services:
- name: frontend
  project: frontend/frontend.csproj
  bindings:
  - protocol: https
    port: 5001
- name: backend
  project: backend/backend.csproj
  bindings:
  - protocol: https
    port: 5002
```

I am using k8s with Docker for Windows.

Output:

```
C:\Development\Temp\microservice> tye --version
0.3.0-alpha.20319.3+4c7d799624984bba1f0622a0aef92b37a9ece5a8
C:\Development\Temp\microservice> tye deploy
Loading Application Details...
Processing Service 'frontend'...
    Applying container defaults...
    Compiling Services...
    Publishing Project...
    Building Docker Image...
        Created Docker Image: 'jamesnk/frontend:1.0.0'
    Pushing Docker Image...
        Pushed docker image: 'jamesnk/frontend:1.0.0'
    Validating Secrets...
    Generating Manifests...
Processing Service 'backend'...
    Applying container defaults...
    Compiling Services...
    Publishing Project...
    Building Docker Image...
        Created Docker Image: 'jamesnk/backend:1.0.0'
    Pushing Docker Image...
        Pushed docker image: 'jamesnk/backend:1.0.0'
    Validating Secrets...
    Generating Manifests...
Deploying Application Manifests...

        Writing output to 'C:\Users\James\AppData\Local\Temp\tmpA3C0.tmp'.
            Error from server (Invalid): error when creating "C:\\Users\\James\\AppData\\Local\\Temp\\tmpA3C0.tmp": Service "frontend" is invalid: spec.ports: Required value
            Error from server (Invalid): error when creating "C:\\Users\\James\\AppData\\Local\\Temp\\tmpA3C0.tmp": Service "backend" is invalid: spec.ports: Required value
Drats! 'deploy' failed:
        'kubectl apply' failed.
```
