### ISSUE TITLE
Expand variable substitution in tye.yaml

### ISSUE THREAD

**Issue by areller** [dotnet/tye#597]
### What should we add or change to make your life better?

Expand syntax for variable substitution in `tye.yaml`
Example:

```
name: example
variables:
  - name: somebin
    value: /usr/bin/somebin
services:
  - name: service-1
     executable: "${somebin} --path ${workdir}/someproject --port ${service:bindings[0]:port}"
     bindings:
       - protocol: http
          port: 8080
```

I know that this was already proposed and is supported in the `connectionString` field, but that was in the context of service discovery. I think that there are other contexts where it can be useful.

These kind of variables will be resolved entirely during the `tye.yaml` build/parse process (before the host starts)

### Why is this important to you?

I was trying to run a legacy project (.NET Framework, IIS) project and I came up with a config that looks like this

```
name: iis
ingress:
  - name: ingress
    bindings:
      - port: 81
    rules:
      - host: mysite1
        service: iis-webapi1
services:
  - name: iis-webapi1
    executable: 'C:\Program Files\IIS Express\iisexpress.exe'
    args: '/path:C:\Users\areller\source\repos\iis-project\iis-website /port:9001'
    bindings:
      - protocol: http
        port: 9001
```

this is verbose, hard for modification and can't be shared among other people.
with variables, it can become:

```
name: iis
variables:
  - name: iis_path
    value: 'C:\Program Files\IIS Express\iisexpress.exe'
ingress:
  - name: ingress
    bindings:
      - port: 81
    rules:
      - host: mysite1
        service: iis-webapi1
services:
  - name: iis-webapi1
    executable: ${iis_path}
    args: '/path:${workdir}\iis-website /port:${service:bindings[0]:port}'
    bindings:
      - protocol: http
        port: 9001
```
