### ISSUE TITLE
Add an option to override a existing Dockerfile

### ISSUE THREAD

**Issue by fjvela** [dotnet/tye#605]
### What should we add or change to make your life better?
Add an option to override an existing Dockerfile in one project

### Why is this important to you?
I have got several projects and it already have got a Dockerfile, add a property to override this Dockerfile it could be cool

For example:

```yaml
name: myapplication
services:
- name: backend
  project: backend/backend.csproj
 dockerfile-ignore: true
  bindings:
  - port: 7000
- name: frontend
  project: frontend/frontend.csproj
  replicas: 2
  bindings:
  - port: 8000
- name: worker
  project: worker/worker.csproj
- name: rabbit
  image: rabbitmq:3-management
  bindings:
    - port: 5672
      protocol: rabbitmq
```
