### ISSUE TITLE
Init commands

### ISSUE THREAD

**Issue by glennc** [dotnet/tye#627]
1. Ability to execute arbitrary commands within the context of a service, meaning you have access to all the configuration setup by Tye to be able to communicate with dependencies if needed.
2. Ability to create pre-canned, named, commands that will automatically appear as UX in the dashboard for you to invoke as-needed.
3. option to automatically execute a command. Automatically executed commands mean we need to do startup in at least this order:
    1. Start all dependencies
    2. Run all init scripts in parallel
    3. Start all services.

strawman example:

```yaml
name: VotingSample
services:
- name: worker
  project: worker/worker.csproj
  init:
    - name: migrate
      cmd: "dotnet ef migrate"
- name: postgres
  image:  postgres
  env:
  - name: POSTGRES_PASSWORD
    value: "pass@word1"
  bindings:
  - port: 5432
    connectionString: Server=${host};Port=${port};User Id=postgres;Password=${env:POSTGRES_PASSWORD};
```
