### ISSUE TITLE
Sample for deploying a backend service using SQL server in k8s 

### ISSUE THREAD

**Issue by quoctuancqt** [dotnet/tye#634]
I'm using Tye to develop my project but I got the issue with the connection to the SQL server in k8s. Here is my tye.yaml
```yaml
name: oppjar
registry: localhost:5000
ingress:
  - name: ingress
    bindings:
      - port: 8080
    rules:
      - path: /
        service: web
      - path: /api
        service: webapi
services:
  - name: mongo
    image: mongo
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: root
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: root
    bindings:
      - port: 27017
        connectionString: "mongodb://${env:MONGO_INITDB_ROOT_USERNAME}:${env:MONGO_INITDB_ROOT_PASSWORD}@${host}:${port}"

  - name: mssql-server
    image: microsoft/mssql-server-linux
    env:
      - name: "MSSQL_SA_PASSWORD"
        value: "P@ssw0rd"
      - name: ACCEPT_EULA
        value: "Y"
    bindings:
      - port: 1433
        connectionString: "Server=${host},${port};Database=Sample;User Id=sa;Password=${env:MSSQL_SA_PASSWORD};"

  - name: webapi
    project: WebApi/WebApi.csproj
    replicas: 2
    env:
      - name: "PathBase"
        value: "/api"
        
  - name: web
    project: Web/Web.csproj
    replicas: 2`
```
When I run `tye deploy --interactive` then complete all configuration, my API service doesn't work because it doesn't connect to the SQL server. 

Could you guys provide me an example to show me how to resolve my issue?
