### ISSUE TITLE
Tye Ingress is not passing query string parameters

### ISSUE THREAD

**Issue by ztittle** [dotnet/tye#638]
### Describe the bug
When Tye is setup to expose ingress, any query string parameters that are sent to it are not passed down to the microservice.

### To Reproduce

1. Setup Ingress in tye.yaml
2. Add a path rule that sends traffic to a given microservice (i.e.). Additionally, I had to configure the microservice to only use http as Ingress does not seem to support http -> https.
```
ingress:
- name: ingress
  bindings:
  - port: 9000
    protocol: https
  rules:
    - service: backend
      path: /api
- name: backend
  project: backend/backend.csproj
  bindings:
  - protocol: http
```
3. Send a request that includes a query string paramter. I.e. `https://localhost:9000/api/weatherforecast?foo=bar`
4. Using logging on the Microservice, it can be observed that the query string is not passed.

### Further technical details

- Include the output of `tye --version`
```
❯ tye --version
0.2.0-alpha.20258.3+bf3bc0913b37e77f5f3ef14f409b3feb794cc447
```
- If possible rerun the command with `-v debug` and include the output

- The platform (Linux/macOS/Windows)
Windows
