### ISSUE TITLE
Add possibility to use docker volumes in tye.yaml

### ISSUE THREAD

**Issue by joelnotified** [dotnet/tye#654]
### What should we add or change to make your life better?
I'm trying to run my entire project in tye, but I can't seem to get Postgres in Docker setup right (on Windows). It seems that with the postgres image for Windows, you are not able to mount a local directory on the host (to store the data). This will give you errors like these:

```
FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
HINT:  The server must be started by the user that owns the data directory.
```

This is documented in several places:
https://github.com/docker/for-win/issues/445
https://forums.docker.com/t/trying-to-get-postgres-to-work-on-persistent-windows-mount-two-issues/12456
https://forums.docker.com/t/data-directory-var-lib-postgresql-data-pgdata-has-wrong-ownership/17963/4

When using `docker-compose`, the workaround seems to be to create a named volume and use that. Like this:

Create volume:
`docker volume create --name postgres-storage -d local`

`docker-compose.yml`:

```
version: '3'
services:
  postgres-dev:
    image: postgres:9.6
    container_name: postgres-dev
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-storage:
    external: true
```

Is this possible to do with tye today, or is there a workaround? I've tried different things, but just can't get it to work.

If there no workaround, could someone point me in the right direction how I can add support for named volumes in tye, would that be wanted?

### Why is this important to you?
Without it I can't run my project in tye 😢

**Comment by joelnotified** [comment]
Ah! Never mind! I didn't read the docs properly. 

For anyone else running into this. Here is what you do in `tye.yaml` (use `name` instead of `source`):

```
  - name: postgres
    image: postgres:9.6
    env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: password
      - name: POSTGRES_DB
        value: postgres
    bindings:
      - port: 5432
    volumes:
      - name: postgres-storage
        target: /var/lib/postgresql/data

```

![image](https://media.tenor.com/images/cbd7e37b64328e8e596df2d339b007d3/tenor.gif)
