### ISSUE TITLE
Tye run and multiple docker networks

### ISSUE THREAD

**Issue by cecilphillip** [dotnet/tye#656]
Let's assume I have a `tye.yaml` that looks like this.
```yaml
services:
  - name: zipkin-service
    image: "openzipkin/zipkin:2.21.7"
    bindings:
      - name: zipkinapiui
        port: 9411
        containerPort: 9411
    tags:
      - infra
  
- name: consul-service
    image: consul:1.8.3
    bindings:
      - name: consulapiui
        port: 8500
        containerPort: 8500
    args: "consul agent -dev -config-dir /etc/consul.d"
    volumes:
      - source: consul.server.json
        target: /etc/consul.d/consul.server.json
    tags:
      - infra
      - consul
```
`tye run --tags=consul` will run the consul container with a default bridge network. Switching to a `tye run --tags=infra` now matches multiple services and will run each container, but now also creates an additional network that it connects the containers to. This means each container now has multiple docker networks they're associated with; a default bridge and a tye_network_something_something.

This is fine for most services, but for networking tools like consul this can be problematic. It needs a to know specifically which IP to bind to if there's multiple networks.
```
Multiple private IPv4 addresses found. Please configure one with 'bind' and/or 'advertise'
```
Looking at the logs, it looks like tye creates the containers, creates the network and then attaches the containers to the network. Are there any downsides to tye creating the network first and then running containers with a `docker run --net=created_network` switch. That way the container would be bound to a single network.
