### ISSUE TITLE
docker-compose like environment variables syntax

### ISSUE THREAD

**Issue by areller** [dotnet/tye#657]
### What should we add or change to make your life better?

There are 3 changes I would like to have

1. Allow to specify environment variables using the [docker-compose syntax](https://docs.docker.com/compose/environment-variables/#set-environment-variables-in-containers)

Example:

```
name: demo-envvars
services:
        - name: console
          project: console/console.csproj
          env:
                  - SOME_VAR_1=SOME_VALUE
                  - SOME_VAR_2="SOME VALUE WITH SPACES"
```

The wouldn't replace the old syntax (having to explicitly write `name` and `value`), but only provide an alternative

2. Allow to pass external environment variables to tye, per the [docker-compose syntax](https://docs.docker.com/compose/environment-variables/#pass-environment-variables-to-containers)

You should be able to specify the names of the environment variables you'd want to pass from the external environment (shell/etc...). Tye would read the values from the environment and pass them into the service

Example:

```
name: demo-envvars
services:
        - name: console
          project: console/console.csproj
          env:
                  - SOME_VAR_1
                  - SOME_VAR_2
```

(This should also work with the existing env vars syntax, if you specify a `name` without a `value`)

3. Allow to specify the path to an env file, per the [docker-compose syntax](https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option)

The env file would have this syntax

```
SOME_VAR_1=SOME_VALUE
SOME_VAR_2="SOME VALUE WITH SPACES"
```

and to reference it in `tye.yaml` you would do

```
name: demo-envvars
services:
        - name: console
          project: console/console.csproj
          env_file:
                  - my_vars_1.env
                  - my_vars_2.env
```

(You would be able to specify multiple files)

### Why is this important to you?

1. The current syntax for environment variables feels overly verbose, compared to docker-compose's syntax, especially, when dealing with 5~10+environment variables.

2. It would make it much more convenient to copy variables from docker-compose to tye or vice-versa
