### ISSUE TITLE
Add support for publishing UDP ports

### ISSUE THREAD

**Issue by jooooel** [dotnet/tye#658]
### What should we add or change to make your life better?
Possibility to publish UDP ports like you can in Docker `1234:1234/udp`.

### Why is this important to you?
I'm trying to run a project in Tye that uses OpenTelemetry and their Jaeger exporter. The Jaeger container requires you to publish UDP ports so that the Jaeger client can send data. This is not currently supported by Tye (AFAIK).

When trying something like this in Tye:

```
- name: jaeger
    image: jaegertracing/all-in-one:1.19
    bindings:
      - name: thrift_compact
        port: 6831/udp
      - name: thrift_binary
        port: 6832/udp
      - name: ui
        port: 16686
```

You get the following error:
`Error parsing tye.yaml: (31, 15): "port" value must be an integer.`

It seems that `port` must be an integer, and looking in `DockerRunner.cs` there seems to be no way of dealing with this. I would be happy to take a shot a providing a PR if you are interested?

**Comment by jkotalik** [comment]
Right now, we support protocol definition via setting `protocol`. 
```yaml
- name: jaeger
    image: jaegertracing/all-in-one:1.19
    bindings:
      - name: thrift_compact
        port: 6831
        protocol: UDP
      - name: thrift_binary
        port: 6832
        protocol: UDP
      - name: ui
        port: 16686
```
That configuration would need to be understood by the Jaeger exporter though. You should be able to use [the following convention](https://github.com/dotnet/tye/blob/master/src/Microsoft.Tye.Extensions.Configuration/TyeConfigurationExtensions.cs#L17) to read the value from config and use it accordingly when configuring Jaeger
