### ISSUE TITLE
Question: Why Tye passes host.docker.internal as HOST and mapped port as PORT instead using docker network alias

### ISSUE THREAD

**Issue by eiximenis** [dotnet/tye#687]
This is just a question :)

I am using tye to run an application with two services. One is nodejs with its own Dockerfile, the other one is a netcore service.

My tye.yaml is simply as:

```
name: testtye
services:
- name: netcoresvc
  project: NetcoreServer/NetcoreServer.csproj
- name: nodeclient
  dockerFile: NodeClient/Dockerfile
  dockerFileContext: NodeClient/
  bindings:
    - port: 3000
  env:
    - name: PORT
      value: 3000
```

Using `tye run` application works as expected, and I have my node client at `localhost:3000` and my netcore server at whatever the ports chosen by tye are.

To connect from the nodejs client to netcore server I use the environment variables provided by tye: `SERVICE__NETCORESVC__HOST` and `SERVICE__NETCORESVC__PORT`

I have observed that `SERVICE__NETCORESVC__HOST` is always `host.docker.internal` and `SERVICE_NETCORESVC_PORT` is the mapped port chosen by tye (different each run).

If I open an interactive session to the nodejs container I can do a `wget -qO-` using the values of these variables, and it works. But **I can also do a `wget -qO- netcoresvc`** and it also works, because tye adds the proxy container using this alias to the docker network.

So my question is: **why is tye using `host.docker.internal` as the name of services instead of using the alias of the docker network?** Is for any specific reason (performance, dns issues,...) that we should we aware of?

Thanks!
