### ISSUE TITLE
'Volumes' specification prevents exposing port to host

### ISSUE THREAD

**Issue by onionhammer** [dotnet/tye#713]
```yml
- name: sql
  image: mcr.microsoft.com/mssql/server
  external: true
  env:
  - name: MSSQL_PID
    value: Developer
  - name: ACCEPT_EULA
    value: Y
  - name: SA_PASSWORD
    value: MySuperSecretPassword!
  bindings:
  - port: 1433
  # volumes:  ## <-- THIS SECTION
  #   - source: .data/mssql
  #     target: /var/opt/mssql
```

The `volumes` portion of the above prevents my host machine from connecting to SQL, but if I omit it it connects without complaint; however without the volume specification the DX suffers in that every time I start tye I have to create a new database from scratch.
