### ISSUE TITLE
Services don't reflect the `host` setting

### ISSUE THREAD

**Issue by petrsvihlik** [dotnet/tye#721]
### Describe the bug
It seems that the [`host`](https://github.com/dotnet/tye/blob/master/docs/reference/schema.md#host-string) is ignored. At least for `ServiceType.Project`.
I need my service to be available for other remote services via a given hostname, not just on localhost.

### To Reproduce
When I set [`services->bindings->host`](https://github.com/dotnet/tye/blob/master/docs/reference/schema.md#host-string) it doesn't get reflected in my app. It just falls back to `localhost`:

https://github.com/dotnet/tye/blob/170876742603e8af260f860b66412946fb05cfe0/src/Microsoft.Tye.Hosting/ProcessRunner.cs#L223

On the other hand, the UI shows the host set correctly:

https://github.com/dotnet/tye/blob/170876742603e8af260f860b66412946fb05cfe0/src/Microsoft.Tye.Hosting/Dashboard/Pages/Index.razor#L96

Temporarily, I overcame the issue by specifying `args: --urls http://*:5000` as you can see in my [yaml](https://github.com/petrsvihlik/WopiHost/pull/105/files#diff-cbc33f9a2d863e8cb06546d9534bf32d37a6eb2d4fedf65852c72160e7d6f4db).

### Further technical details

- `tye --version`: 0.5.0-alpha.20520.1+739de2eeb94f0246f50fa4993e953abb4b0da18a
- Platform: Windows

**Comment by robertsundstrom** [comment]
I have experienced the same issue.

**Comment by robertsundstrom** [comment]
Issue is still in ```0.7.0-alpha.21205.1+ad2d7cac132e46d9bd9e1c1c064fd19f35459307```.

**Comment by jkotalik** [comment]
Extra notes from the other issue:
### Describe the bug
The  ```host``` parameter in ```bindings``` section in tye.yml is not passed to the service/app.

As a result the service is not binding to the specified IP address or hostname, and is still ```localhost```.

The issue was first reported in #721 . There you find more details about what line of code.

### To Reproduce

Create a web project:

```
dotnet new web -o TestWebApp
cd TestWebApp
```

This is optional (just copy the config below):

```
tye init
```

Add the bindings section (substitute YOUR-IP-ADDRESS with your own IP Address or host name):

```
name: testwebapp
services:
- name: testwebapp
  project: TestWebApp.csproj
  bindings:
    - name: Test
      host: <YOUR-IP-ADDRESS>
      port: 5643
```

### Further technical details

Tye version: 0.7.0-alpha.21205.1+ad2d7cac132e46d9bd9e1c1c064fd19f35459307.
.NET version: 5.0.200

**Comment by robertsundstrom** [comment]
I was hoping this setting would make it possible to access a service from a remote client, like a mobile phone.

Is there a way that currently works?

**Comment by jt-pt-dev** [comment]
I would love to see this working as well. The local dev story with tye is great. If I want to share with other team members or test on a mobile device the binding to localhost is a problem. Being able to specify a host would solve this.

**Comment by robertsundstrom** [comment]
@jt-pt-dev It seems that people are instead using Ingress in certain scenarios. Like with localhost.

So do I in my system in order to let my web app access the micro services.

This feature should still be fixed though, since it is a bug.

I see it useful to bind a service to other hosts than localhost.

**Comment by robertsundstrom** [comment]
Oh. I forgot: I wanted to use the ```host```setting to bind my service to the IP-address, in order to access the service remotely from a phone.

**Comment by jt-pt-dev** [comment]
Yep, that is one of my use cases as well.

**Comment by robertsundstrom** [comment]
My workaround for this is using Nginx since I have a lot of services, and Ingress does not work with WebSocket requests.

tye.yaml:
```yaml
- name: frontend
  project: Frontend/Frontend.csproj
  bindings:
  - port: 5001
    protocol: https

- name: fackend
  project: Backend/Backend.csproj
  bindings:
  - port: 5002
    protocol: https

- name: nginx
  image: nginx
  bindings:
    - protocol: https
      port: 8080
  volumes:
    - source: nginx.conf
      target: /etc/nginx/templates/default.conf.template
    - source: certs
      target: /etc/nginx/certs
```

nginx.conf:
```
upstream frontend {
    # Using environment variables generated by Tye
    server ${FRONTEND_SERVICE_HOST}:${FRONTEND_SERVICE_PORT};
}

upstream backend {
    server ${BACKEND_SERVICE_HOST}:${BACKEND_SERVICE_PORT};
}

server {
    listen ${NGINX_SERVICE_PORT};
    server_name localhost;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/certs/localhost.crt;
    ssl_certificate_key /etc/nginx/certs/localhost.key;

    location / {
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;

        proxy_pass https://frontend/;

        resolver 127.0.0.11;
    }

    location /backend/ {
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;

        proxy_pass https://backend/;

        resolver 127.0.0.11;
    }
}
```

**Comment by mpp** [comment]
Hi! The issue is still present if I can't use the nginx image with docker.
Is there something else I can do about it?

I think that downloading nginx and run it as an executable might be a solution, can you help me with the configuration?
I'm trying on my own and I don't know anything about it... it's a bit hard.
It seems like i cannot use the environment variables that Tye generates.



Thanks in advance!

**Comment by mpp** [comment]
I made a C# command line program that substitute the environment variables from a template and overwrite the nginx.conf file before running it.
It seems to be working!
![image](https://github.com/dotnet/tye/assets/454298/4bea001d-15fd-4ecb-b4a7-82707a0d7a33)

```C#
using System.Collections;
using System.Diagnostics;

Console.WriteLine("Nginx Config File pre-processor");

if (args.Length != 2)
{
    Console.Error.WriteLine($"Syntax: ConsoleApp1 <template_file> <nginx_working_directory>");
    return;
}

var nginxTemplateFile = args[0];
var nginxWorkingDirectory = args[1];
var nginxConfFile = Path.Combine(nginxWorkingDirectory, "./conf/nginx.conf");
var nginxEXE = Path.Combine(nginxWorkingDirectory, "./nginx.exe");

if (!File.Exists(nginxTemplateFile))
{
    Console.Error.WriteLine($"Cannot find the nginx template file at [{nginxTemplateFile}]");
    return;
}

if (!File.Exists(nginxConfFile))
{
    Console.Error.WriteLine($"Cannot find the nginx config file at [{nginxConfFile}]");
    return;
}

var config = File.ReadAllText(nginxTemplateFile);

var variables = Environment.GetEnvironmentVariables();

foreach (DictionaryEntry item in variables)
{
    if (item.Value is string stringValue)
        config = config.Replace($"${{{item.Key}}}", stringValue);
}

Console.WriteLine($"The new nginx configuration is: {Environment.NewLine}{config}");
File.WriteAllText(nginxConfFile, config);

Console.WriteLine($"Starting nginx");

Process cmdDotnet = new();
cmdDotnet.StartInfo.FileName = nginxEXE;
cmdDotnet.StartInfo.RedirectStandardInput = true;
cmdDotnet.StartInfo.RedirectStandardOutput = true;
cmdDotnet.StartInfo.CreateNoWindow = false;
cmdDotnet.StartInfo.UseShellExecute = false;
cmdDotnet.StartInfo.WorkingDirectory = nginxWorkingDirectory;
cmdDotnet.Start();
cmdDotnet.StandardInput.WriteLine("cmd started");
cmdDotnet.StandardInput.Flush();
cmdDotnet.StandardInput.Close();
cmdDotnet.WaitForExit();

Console.ReadLine();
```

Now the tye.yaml can be:

```YAML
name: tyetests

services:

- name: blazor-app1
  project: BlazorApp1/BlazorApp1.csproj
  bindings:
    - protocol: http
      port: 9000
  liveness:
    http:
      path: /app1/healthy
  readiness:
    http:
      path: /app1/ready

- name: nginx
  project: ConsoleApp1/ConsoleApp1.csproj
  args: "D:\\Workspace\\TyeTests\\TyeTestApp\\ConsoleApp1\\nginx.conf.template D:\\Workspace\\TyeTests\\TyeTestApp\\openresty-1.21.4.2-win64"
  bindings:
    - protocol: http
      port: 8081
```

Where the template is (I'm on windows):
```YAML
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    keepalive_timeout  65;
	
    upstream app1 {
        server ${BLAZOR-APP1_SERVICE_HOST}:${BLAZOR-APP1_SERVICE_PORT};
    }

    server {
        listen ${NGINX_SERVICE_PORT};
        server_name localhost;

        location / {
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header   Connection keep-alive;
            proxy_set_header   Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;

            proxy_pass http://app1/;
        }
    }
}
```

Now I need to understand how to set the host to be any IP but I'm sure it is somewhere in the nginx documentation!
