### ISSUE TITLE
Allow targetPort to be specified in tye.yaml

### ISSUE THREAD

**Issue by jongio** [dotnet/tye#724]
### What should we add or change to make your life better?

I need to set targetPort to a different value than port.  Right now, tye uses the value that is set in port:

See:
https://github.com/dotnet/tye/blob/f27905b09a7e185e229b998978c64dd874103d10/src/Microsoft.Tye.Core/KubernetesManifestGenerator.cs#L186

### Why is this important to you?

Because my service container exposes port 1080, and my container exposes 80

This is the desired output.

See that targetPort is diff than port.

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file ./src/net/docker-compose.yml -o ./pac/k8s/net
      --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: memealyzernetwebapp
  name: memealyzernetwebapp
spec:
  ports:
  - name: "1080"
    port: 1080
    targetPort: 80
  - name: "1443"
    port: 1443
    targetPort: 443
  selector:
    io.kompose.service: memealyzernetwebapp
status:
  loadBalancer: {}

```

azsdke2e
azsdke2e0
