### ISSUE TITLE
containerPort contains port value

### ISSUE THREAD

**Issue by jongio** [dotnet/tye#725]
### Describe the bug

containerPort is written to manifest with port value

See: 
https://github.com/dotnet/tye/blob/f27905b09a7e185e229b998978c64dd874103d10/src/Microsoft.Tye.Core/KubernetesManifestGenerator.cs#L377

### To Reproduce

This tye.yaml
```yaml
- name: memealyzernetwebapp
  project: ${TYE_ROOT}/src/net/WebApp/WebApp.csproj
  bindings:
    - port: 1111
      protocol: tcp
      containerPort: 2222
  env_file: 
    - ${TYE_ROOT}/${DOTENV_FILENAME}
  tags:
    - dev
    - staging
    - prod
```

Produces this:
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: memealyzernetwebapp
  labels:
    app.kubernetes.io/name: 'memealyzernetwebapp'
    app.kubernetes.io/part-of: 'memealyzer'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: memealyzernetwebapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 'memealyzernetwebapp'
        app.kubernetes.io/part-of: 'memealyzer'
    spec:
      containers:
      - name: memealyzernetwebapp
        image: memealyzerdevacr.azurecr.io/memealyzernetwebapp:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 1111
```

> Notice that containerPort is 1111, which is port's value.  It should be 2222

### Further technical details

- Include the output of `tye --version`

0.5.0-alpha.20520.1+739de2eeb94f0246f50fa4993e953abb4b0da18a

- If possible rerun the command with `-v debug` and include the output
- The platform (Linux/macOS/Windows)

WSL2

azsdke2e
azsdke2e0

**Comment by jkotalik** [comment]
Yeah this seems like just a straight up bug 😄

**Comment by jongio** [comment]
@tebeco / @jkotalik - Just a heads up that this will be more then change that one line of code.  The semantics on how containerPort, targetPort, and port are thought about in tye will need to be thought through.  For example, when do you output a containerPort to the manifest?  Right now it is only if we have a port value.  I believe the default of containerPort: 80 would be better, but not sure.  

Also, when you parse containerPort from the yaml, what is the default value that is extracted and how do you test for null?

**Comment by tebeco** [comment]
Yeah, just saw that, converted back to draft I might even close it because I think you might go faster than me for this PR @jongio 

I saw you opened lots of ticket lattely and some looked from the outside "possible to take a look at it"
I though this would be an opportunity for me to contribute a bit for OSS but it's not that easy :D

**Comment by jongio** [comment]
Here's what I recommend:

If tye.yaml has `containerPort`, then use it for both `containerPort` in the deployment and `targetPort` in the service
If tye.yaml doesn't have `containerPort`, then use `80` for http and `443` for https for both `containerPort` and `targetPort`.

I personally do not see a scenario where `containerPort` or `targetPort` should be equal to `port`

@jkotalik to confirm the logic above, but @tebeco if you want to take a stab at updating to that, you are more than welcome to mod your PR.

**Comment by tebeco** [comment]
> then use 80 for http and 443 for https for both containerPort and targetPort.

Unrelated note, but opening port less than 1024 means running as `root` right
I though that as a general recommendation running code as root was not the way to go

**Comment by jongio** [comment]
I believe tye defaults to 80 in the container that's why I suggested we align to it. 

Can you verify that it defaults to 80 in container as-is?

**Comment by tebeco** [comment]
yeah I think so yeah. That just got on my mind as we had to fix that to go to production last month.
this is enforced by company for good reasons ;)

**Comment by jongio** [comment]
Do you want to try and get a PR in for this?… If not we can take a look first thing next week￼

**Comment by tebeco** [comment]
I'm currently wondering if this one is easier to land than the one on ingress.
That's why I changed this one to draft

On the other hand updating `ingress manifest` to `v1` is more complexe due to the way Kubernetes documentation is "oriented" but that's out of topic for this issue

**Comment by jongio** [comment]
For me personally, getting the ports fixed is higher pri and likely easier to get right.  If you want to update your PR with the logic above and then we can discuss with Justin on Monday.

**Comment by tebeco** [comment]
Understood though it's almost 6PM here so I won't be very reactive on that one but yes why not I might try to take a look at it ^^

to be clear if anyone manage to make a quick fix feel free to close my PR I don't care if someone else fix it ^^
At the end of the day what matters will be that it works

**Comment by tebeco** [comment]
```yaml
name: foobar
services:
- name: thewebapione
  project: src/TheWebapiOne/TheWebapiOne.csproj
  bindings:
    - port: 1111
      protocol: http
      containerPort: 2222
```

The `port` here is supposed to be use for something else than `tye run` during dev to enforce Kestrel binding ?
I'm not sure what's this
![image](https://user-images.githubusercontent.com/2266487/97820021-6aff4900-1cac-11eb-9fa4-fadcd52c8d40.png)
