### ISSUE TITLE
Ingress to AKS not working

### ISSUE THREAD

**Issue by jongio** [dotnet/tye#729]
### Describe the bug

I'm not able to get ingress to AKS working.

### To Reproduce

Here's my tye.yaml ingress:

```yaml
ingress:
  - name: 1080
    bindings:
      - port: 1080
    rules:
      - path: /
        service: memealyzernetwebapp
  - name: 2080
    bindings: 
      - port: 2080
    rules:
      - path: /images
        service: memealyzernetapi
      - path: /image
        service: memealyzernetapi
      - path: /config
        service: memealyzernetapi
      - path: /imagehub
        service: memealyzernetapi
```

When I run `tye generate` I do not see any Ingress settings generated.

### Further technical details

- Include the output of `tye --version`
0.5.0-alpha.20520.1+739de2eeb94f0246f50fa4993e953abb4b0da18a
- If possible rerun the command with `-v debug` and include the output
- The platform (Linux/macOS/Windows)
WSL2

azsdke2e
azsdke2e0

**Comment by jongio** [comment]
This works locally, but not for AKS.

Here's what I have in Ingress/tye.yaml
```yaml
ingress:
  - name: ingress
    rules:
      - path: /
        service: memealyzernetwebapp
      - path: /images
        service: memealyzernetapi
        preservePath: true
      - path: /image
        service: memealyzernetapi
        preservePath: true
      - path: /config
        service: memealyzernetapi
        preservePath: true
      - path: /imagehub
        service: memealyzernetapi
        preservePath: true
      - path: /api/negotiate
        service: memealyzernetfunction
        preservePath: true
    tags:
      - dev
      - staging
      - prod
```
Here's what is generated:
```yaml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/rewrite-target: '/$2'
  labels:
    app.kubernetes.io/part-of: 'memealyzer'
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: memealyzernetwebapp
          servicePort: 1080
        path: /()(.*)
      - backend:
          serviceName: memealyzernetapi
          servicePort: 2080
        path: /()(.*)
      - backend:
          serviceName: memealyzernetapi
          servicePort: 2080
        path: /()(.*)
      - backend:
          serviceName: memealyzernetapi
          servicePort: 2080
        path: /()(.*)
      - backend:
          serviceName: memealyzernetapi
          servicePort: 2080
        path: /()(.*)
```


Looks like path is not reflecting what is in tye.yaml:path
