### ISSUE TITLE
watch doesn't work for Blazor WASM

### ISSUE THREAD

**Issue by jongio** [dotnet/tye#741]
### Describe the bug

using --watch.  Doesn't see Blazor file changes.  Need to stop and restart tye for every change.

### To Reproduce

Create Blazor project
Start tye with watch
Make changes
Don't see update

### Further technical details

- Include the output of `tye --version`
- If possible rerun the command with `-v debug` and include the output
- The platform (Linux/macOS/Windows)

azsdke2e
azsdke2e1

**Comment by Megasware128** [comment]
Seems to be issue with razor files (and also cshtml in non blazor projects) specifically. For me if I edit a cs file it does rebuild.

**Comment by codebangkok** [comment]
You can use tye init and add config to tye.yaml

Example

```
name: blazor
services:
- name: blazorwasm
  project: BlazorWasm/BlazorWasm.csproj
  bindings:
    - port: 5001
      protocol: https
```
