### ISSUE TITLE
There is no way of running a service on many ports! For instance I can't work well with couchbase 

### ISSUE THREAD

**Issue by gedeoni** [dotnet/tye#744]
Running Couchbase Image need the opening of many ports.
- The normal docker command is docker run -p 8091-8094:8091-8094 -p 11210:11210 couchbase-server
However, Tye only gives the ability to expose one port. I just wish that could be fixed and we would be able to run services that have multiple ports

**Comment by jkotalik** [comment]
Maybe this wouldn't work, but you can have multiple bindings for a service. Ex:
```yaml
services:
  - name: couchbase
    image: couchbase
    bindings:
      - name: binding1
        port: 8091
      - name: binding
        port: 8092
      - name: binding
        port: 8093
      - name: binding
        port: 8094
      - name: binding
        port: 11210
```

Does that fix your scenario?
