### ISSUE TITLE
Support for ExternalName Service Type

### ISSUE THREAD

**Issue by jongio** [dotnet/tye#749]
### What should we add or change to make your life better?

I have aks with some services

I have an AF deployed to an app service.

Locally, I have this:
```yaml
- name: memealyzernetfunction
    azureFunction: ${TYE_ROOT}/src/net/Services/Functions/
    bindings:
      - port: 3080
        protocol: http
    tags:
      - dev
```

and ingress:
```yaml
      - path: /api/negotiate
        service: memealyzernetfunction
        preservePath: true
```

When I deploy to prod, I'm deploying the AF on my own with a script.

But I want to wire up the function as an externalName service.  

This is possible with type: ExternalName service
https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-mapping-external-services
### Why is this important to you?

Because this reduces the amount of config I need in my front end apps.  Because I can setup Ingress to map to the service without having to have the function on a different port in prod.
