### ISSUE TITLE
Should containerPort default to 80 for image references?

### ISSUE THREAD

**Issue by jongio** [dotnet/tye#758]
### What should we add or change to make your life better?

In the case of k8s deployment, defaulting to 80 makes sense.

But in this scenario, having it be equal to port makes sense.

We may want to revisit and allow port to be specificed like this "10000:10000"  (port:containerPort)

For Azurite, you need to map 10000:10000.  With this:
```yaml
services:
  - name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    bindings:
      - name: blob
        port: 10000
        protocol: http
      - name: queue
        port: 10001
        protocol: http
    tags:
      - dev

```

It will map like this: 10000:80, which won't work.

So you need to specify containerPort
```
services:
  - name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    bindings:
      - name: blob
        port: 10000
        containerPort: 10000
        protocol: http
      - name: queue
        port: 10001
        containerPort: 10001
        protocol: http
    tags:
      - dev
```

### Why is this important to you?

If we default to containerPort = port, then I would only need to specify one port.

I honestly prefer to use the standard docker port mapping construct 10000:10000 for port.  And I think people coming from that world would too.

azsdke2e
azsdke2e2
