### ISSUE TITLE
Cant connect to my MySQL container in tye

### ISSUE THREAD

**Issue by LukePammant** [dotnet/tye#770]
### Describe the bug
When I run my netcoreapp3.1 service using Tye I can't connect the the MySQL container (also run via Tye). I get the following error: `MySql.Data.MySqlClient.MySqlException : Unable to connect to any of the specified MySQL hosts.`

What I've tried:
- I verified that the MySQL container and my service's container are in the same docker network
- I *can* connect to the MySQL when running the service locally using 'localhost:3306'
- I *can* ping the MySQL container via the container name 'auth-my-sql' when I `docker exec` into the Tye container running my service and it successfully resolves the IP
- I *can* connect to the MySQL container via my own docker container running my service if I put it on the same network

It seems to be only when I run it in via Tye that it doesn't work

### To Reproduce
I have the following in my tye.yml:
```
- name: Authentication-DB-Seed
  project: Authentication/Authentication.csproj
  args: /seed
  env:
    - ConnectionStrings__DefaultConnection="Server=auth-my-sql;Port=3306;Database=chronos-auth;Uid=root;Pwd=P@ssw0rd

- name: auth-my-sql
  image: mysql
  bindings:
    - port: 3306
  env:
    - MYSQL_ROOT_PASSWORD=P@ssw0rd
```

### Further technical details

- tye --version= 0.5.0-alpha.20555.1+fae47325b0c8d7dafcdec5d1248191b24b2adc23
- Platform is WSL2 on Ubuntu 20.0.4 w/ Docker Desktop & WSL integration
