### ISSUE TITLE
.env file variables are not replaced

### ISSUE THREAD

**Issue by jongio** [dotnet/tye#772]
### What should we add or change to make your life better?
```
BASENAME=memealyzerdev

# TERRAFORM VARS
TF_VAR_basename=${BASENAME}
```

Tye generates like this:
```
    spec:
      containers:
      - name: memealyzernetwebapp
        image: memealyzernetwebapp:1.0.9
        imagePullPolicy: Always
        env:
        - name: BASENAME
          value: 'memealyzerstaging'
        - name: TF_VAR_basename
          value: '${BASENAME}'
```

I would like the env vars to be replaced by tye.

### Why is this important to you?

So I don't have to do it myself

azsdke2e
azsdke2e2
