### ISSUE TITLE
Dapr support for docker containers

### ISSUE THREAD

**Issue by LukePammant** [dotnet/tye#775]
### What should we add or change to make your life better?
Spin up dapr sidecars for docker containers.

### Why is this important to you?
I have some nodeJS services along with .NET services and both use dapr. The NodeJS services start as a docker container and I need a way to spin up the dapr sidecar. It looks like the dapr extension only works for `project` services.

**Comment by LukePammant** [comment]
I am able to get dapr running via `executable` but can't get communication between the docker container and the dapr executable because they aren't in the same network and I don't have control over the network Tye starts the docker containers on. I got communication working between the docker container and the executable by changing the dapr host to point to 'docker.host.internal' but that feels klugy.

I could run dapr via the dapr docker image but Tye doesn't give the ability to override the command so I can provide app ports and such. 

``` yaml
- name: Captains
  dockerFile: ./Captains/Dockerfile
  dockerFileContext: ./Captains
  bindings:
    - port: 6014
  env:
    - DAPR_HTTP_PORT=3514
    - DAPR_HOST=host.docker.internal

- name: Captains-dapr
  workingDirectory: ./Captains
  executable: /usr/local/bin/daprd
  args: --app-port 6014 --app-id captains --dapr-http-port 3514 --dapr-grpc-port 35014 --placement-address localhost:50005 --components-path ../components -metrics-port 35114
```
