### ISSUE TITLE
Prometheus / Graphana

### ISSUE THREAD

**Issue by tomasforsman** [dotnet/tye#783]
I saw in a post somewhere that you were working on easy integration with logging, prometheus and graphana. How have things come along with that? Are there any samples on how to do that? I'm not experienced with using prometheus so I figured I might give it a go with Tye if it's something you've worked at.

**Comment by hikalkan** [comment]
I am having trouble when I try to integrate prometheus. I use prometheus docker image.

**tye.yml (related parts)**

```yml
- name: prometheus
  image: prom/prometheus
  bindings:
    - port: 9090
  volumes:
    - source: prometheus.yml
      target: /etc/prometheus/prometheus.yml

- name: saas-service
  project: saas/src/SaasService.HttpApi.Host/SaasService.HttpApi.Host.csproj
  bindings:
    - protocol: https
      port: 44381
```

**prometheus.yml**

````yml
global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'saas-service'
    scheme: https
    static_configs:
    - targets: ['saas-service:44381']
      labels:
        alias: "saas-service"
````

(I also tried 'localhost:44381', '127.0.0.1:44381')

**Prometheus UI**

![image](https://user-images.githubusercontent.com/1210527/109928395-76a06200-7cd6-11eb-8566-078806578937.png)

It seems that Prometheus can not access to my service (that is running locally).

**So, Question is**: How an application in a container can access to the service URL that is added as project?
