### ISSUE TITLE
Mgt port binding not being mapped to rabbitmq container

### ISSUE THREAD

**Issue by mcain12** [dotnet/tye#825]
I am running a simple example with rabbitmq.  The sample works, but I am not able to access the rabbitmq management portal when running through tye.  I believe I have the port mapped properly and the url comes up correct in the tye dashboard, but when I try to connect to it I get nothing.  

Here is my tye.yml file..

# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: ims
services:
- name: inventoryservice
  project: InventoryService/InventoryService.csproj
- name: orderservice
  project: OrderService/OrderService.csproj
- name: rabbit
  image: rabbitmq:3-management
  bindings:
    - port: 5672
      name: rabbitmq
      protocol: amqp
    - port: 15672
      name: rabbitmgt
      protocol: http

![image](https://user-images.githubusercontent.com/73498199/100118001-678e5600-2e43-11eb-953b-be0824aa1e9c.png)

I am receiving an empty response...
![image](https://user-images.githubusercontent.com/73498199/100118184-99072180-2e43-11eb-91a6-2d2d81717183.png)

**Comment by javis86** [comment]
Try this:
````yaml
- name: rabbit
  image: rabbitmq:3-management
  bindings:
    - port: 5672
      name: rabbit
      protocol: amqp
    - port: 15672
      name: rabbit-mgt
      containerPort: 15672
      protocol: http
````
