### ISSUE TITLE
Nested configuration must have the same "name" in the tye.yaml

### ISSUE THREAD

**Issue by mmisztal1980** [dotnet/tye#847]
### Some details

**How many services are in your application? (including things like databases, redis):**

- [ ] 1-2
- [] 3-5
- [x] 6-10
- [ ] 10+

**What did you use tye for?**

- [x] Local development
- [ ] Deployment

**How is your code organized?**

- [x] One service per repo
- [ ] Many services in one big repo
- [ ] Other (please explain)

### What did you think of tye?

I think the `Nested configuration must have the same "name"` constraint is absurd. I'm using Tye with multirepo approach, I'm keeping all shared & long running infrastructure in an external repository, with reuse in mind. I want all of my subsequent projects to capitalize on the tye file(s) in that repo

Example:

**tye.yaml**
```
name: demo
extensions:
- name: dapr
services:
- name: core-local-infrastructure
  repository: {repository address} --branch main
- name: demo-api1
  project: demo/demo-api1/src/Demo.Api1/Demo.Api1.csproj
- name: demo-svc
  project: demo/demo-svc/src/Demo.Service/Demo.Service.csproj
```

**core-local-infrastructure/tye.yaml**
```
name: core-local-infrastructure
services:
- name: telemetry                              # includes ELK & Jaeger
  include: ./telemetry.yaml
- name: storage                                  # includes Posgres & PgAdmin
  include: ./storage.yaml
- name: messaging                             # includes RabbitMQ
  include: ./messaging.yaml
- name: service-discovery                   # includes Consul
  include: ./service-discovery.yaml
```

Question:
- Why is the said constraint in effectin the 1st place? What purpose does it serve? Right now it seems to be counterproductive - forcing me to name everything in the same way across multiple projects?
- Why not match nested tyes' name vs the parent tyes' `services[i].name` instead?
