### ISSUE TITLE
Can I use project tye with a kubernetes CRON job?

### ISSUE THREAD

**Issue by vbodurov** [dotnet/tye#849]
I have a kubernetes CRON job defines as:
```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  schedule: <schedule here>
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 180
          containers:
            - name: my-cronjob
              image: <image path here>
```

How can I pass the yaml manifest to tye yaml so that it will create CRON job?
