### ISSUE TITLE
using preservePath in ingressRule in tye.yaml results in string duplication in the request path

### ISSUE THREAD

**Issue by andreakn** [dotnet/tye#877]
### Describe the bug
using preservePath in ingressRule in tye.yaml results in string duplication in the request path
I have the following ingress rules: 

```
ingress:
  - name: ingress
    bindings:
      - port: 8080      
    rules:
      - path: /
        service: myservice1
      - path: /auth
        service: myservice2
        preservePath: true

```

when making a request to http://localhost:8080/auth/whatever
the request comes in to myservice2 with path /auth/whateverwhatever

if I don't use preservePath:true the request comes in with path /whatever

I would really like the incoming request path to be /auth/whatever

### To Reproduce
set up ingress with preservePath:true and observe which path comes in on requests

### Further technical details
tye version: 0.5.0-alpha.20555.1+fae47325b0c8d7dafcdec5d1248191b24b2adc23
OS: Windows 10 pro
