### ISSUE TITLE
Ingress using v1beta1 with kubectl v1.19.3

### ISSUE THREAD

**Issue by jongio** [dotnet/tye#913]
### Describe the bug

I'm deploying to a cluster with v1.19.3

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:08Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

Tye is deploying v1beta1 and I get this warning
`Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress`

Ingress is correctly generated in manifest.
```
...
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/rewrite-target: '/$2'
  labels:
    app.kubernetes.io/part-of: 'memealyzer'
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: memealyzernetwebapp
            port:
              number: 1080
        pathType: Prefix
        path: /()(.*)
      - backend:
          service:
            name: memealyzernetapi
            port:
              number: 2080
        pathType: Prefix
        path: /()(images.*)
      - backend:
          service:
            name: memealyzernetapi
            port:
              number: 2080
        pathType: Prefix
        path: /()(image.*)
      - backend:
          service:
            name: memealyzernetapi
            port:
              number: 2080
        pathType: Prefix
        path: /()(config.*)
      - backend:
          service:
            name: memealyzernetapi
            port:
              number: 2080
        pathType: Prefix
        path: /()(imagehub.*)
...

```

I believe the issue is due to this: `kubectl apply -f https://aka.ms/tye/ingress/deploy` using v1beta1

### Further technical details

0.7.0-alpha.21070.7+eb3b50699b7a5f2d0997a5cc8c5185d056dde8ec

azsdke2e
azsdke2e1
