### ISSUE TITLE
Pass in docker arguments to image service

### ISSUE THREAD

**Issue by jonathan-caddy** [dotnet/tye#919]
I want to include azurite as a service in my tye.yaml config.  I can achieve this quite easily:

```
services:
- name: azurite
  image: mcr.microsoft.com/azure-storage/azurite
  bindings:
    - port: 10000
      name: blob
    - port: 10001
      name: queue
```

However, I want specify the local storage paths so that I can persist some data. There is a straightforward docker command line parameter, i.e. "-v c:/azurite:/data", to achieve this easily.

```
docker run -p 10000:10000 -p 10001:10001 -v c:/azurite:/data mcr.microsoft.com/azure-storage/azurite
```

Can I include this parameter in my tye.yaml?  I have tried the "args" property with no luck.

**Comment by jongio** [comment]
Use `volumes` for volume mounts
![image](https://user-images.githubusercontent.com/2163001/105900707-45df5580-5fd1-11eb-8b28-e5bd0188f516.png)
![image](https://user-images.githubusercontent.com/2163001/105900723-4bd53680-5fd1-11eb-8b07-e38c4d0c60b2.png)


Use `args` if you want to pass args to azurite

![image](https://user-images.githubusercontent.com/2163001/105900634-2c3e0e00-5fd1-11eb-89aa-fd74cdfaf5e7.png)


```
services:
  - name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    volumes:
      - source: /mnt/c/azurite
        target: /data
    args: "azurite --skipApiVersionCheck"
    bindings:
      - name: blob
        port: 10000
        containerPort: 10000
        protocol: http
      - name: queue
        port: 10001
        containerPort: 10001
        protocol: http
      - name: table
        port: 10002
        containerPort: 10002
        protocol: http
    tags:
      - local
```

**Comment by jonathan-caddy** [comment]
Thanks @jongio - that has me up and running. New to tye and docker so apologies for stupidity all round.  Interestingly the addition of the "args" property above must override any default args. When I ran it exactly as you specified my blobHost and queueHost azurite properties defaulted back to 127.0.0.1, which meant that I could not connect to the azurite service outside the docker container. I had to explicitly set blobHost and queueHost in the args as below.

```
services:
- name: azurite
  image: mcr.microsoft.com/azure-storage/azurite
  volumes:
    - source: /Users/[username]/Projects/Resources/Azurite
      target: /data
  args: "azurite --skipApiVersionCheck --blobHost 0.0.0.0 --queueHost 0.0.0.0 --location /data"
  bindings:
    - name: blob
      port: 10000
      containerPort: 10000
      protocol: http
    - name: queue
      port: 10001
      containerPort: 10001
      protocol: http
```

Am I right in thinking if you set the "args" property it overrides any container image defaults? 

BTW - I am just touching the surface of tye and i can see it saving me tedium every day I fire up my dev environment. Thanks all round.
