### ISSUE TITLE
Add 'follow logs' checkbox

### ISSUE THREAD

**Issue by onionhammer** [dotnet/tye#992]
### What should we add or change to make your life better?
The logs currently continues to append but doesnt scroll as new logs are being added. It would be great if there was a 'follow logs' checkbox to automatically scroll down as new log lines are appended.

This can be done easily with CSS and a checkbox;

```css
.FollowLogs
{
    scroll-snap-type: y mandatory;
}
```
